openshift/sdn

- pkg/network/node/iptables.go
- pkg/network/node/node.go
If a packet has already been marked by other kube-proxy rules for masquerade, don't run it through the OPENSHIFT-MASQUERADE chain for further twiddling.
Most notably, this chain is used for Egress IPs.
This change fixes a bug where egress IPs can't access services via their ExternalIP. (bz [1726045](https://bugzilla.redhat.com/show_bug.cgi?id=1726045))
> Bug 1726045: skip OPENSHIFT-MASQ for traffic already marked for masquerade

- cmd/sdn-cni-plugin/openshift-sdn_linux.go
- pkg/network/node/ovscontroller.go
This addresses the bug described [here](https://jira.coreos.com/browse/SDN-493)
We want to allow DNS packets to be routed through the metadata IP as this is sometimes used by internal mechanism to these providers when performing certain networking tasks.
> Allow DNS port when performing iptables filtering on cloud provider metadata IP

- pkg/network/node/iptables.go
PR #13 changed the source rule for OPENSHIFT-MASQUERADE. However, rolling out source-rule changes on a running system isn't clean. Easier to leave the source-rule unchanged, and just add a rule first in the chain that gets us where we want to be.
So, -j RETURN for traffic that's already marked for MASQ.
> iptables: partial #13 revert, skip masq in chain

- images/kube-proxy/scripts/ip6tables
- images/kube-proxy/scripts/ip6tables-restore
- images/kube-proxy/scripts/ip6tables-save
- images/kube-proxy/scripts/iptables
- images/kube-proxy/scripts/iptables-restore
- images/kube-proxy/scripts/iptables-save
#14 originally had duplicate copies of the iptables scripts and was then rewritten to share the ones the sdn image uses but Sally forgot to remove the duplicates and I didn't notice
> Drop accidentally not-dropped duplicate iptables scripts

- pkg/network/node/ovscontroller.go
If a packet is being sent over the VXLAN to a remote egress IP, we have to tell conntrack to remember the packet first, so that when we get the response it will be recognized as such (and thus accepted regardless of NetworkPolicy).
(Note that we can't just pass *all* outbound packets to conntrack; calling `ct(commit)` on a packet will make iptables think it has already processed the packet, so we can't commit anything that will need to be masqueraded, DNAT'ed, etc, later.)
> Bug 1700431: Pass egress IP packets to conntrack

- pkg/network/proxyimpl/hybrid/proxy.go
- pkg/openshift-sdn/proxy.go
QE pointed out that it's not easy to see if changing the unidling setting has taken effect. So, add a few simple log lines.
> proxy: add a bit more logging around proxy type and sync status

- pkg/network/node/multitenant.go
- pkg/network/node/node.go
- pkg/network/node/ovscontroller.go
- pkg/network/node/pod.go
- pkg/network/node/sdn_controller.go
This is a fix for [BUG 1723924](https://bugzilla.redhat.com/show_bug.cgi?id=1723924)
FIX for 4.X on origin, see linked PR's in origin
4.1:
https://github.com/openshift/origin/pull/23537
3.11:
https://github.com/openshift/origin/pull/23522
The problem:
As mentioned in the link above, when the openshift networking process dies, the "podManager" object and its attribute "runningPods" is wiped for memory, which can lead to stateful inconsistencies 
with openflow ports concerning pods from a multicast-enabled namespaces 
The fix:
We now initialize the "podManager" with the initial state of all running pods when the process is booted, as such we will have a synchronized state.
> Bug 1740741: Initializing runningPods on SDN bootup for 4.x

- .gitignore
- Makefile
- images/node/Dockerfile
- images/node/Dockerfile.rhel
- pkg/network/node/node.go
- pkg/network/node/pod.go
With https://github.com/openshift/cluster-network-operator/pull/288 merged, openshift-sdn gets its upstream CNI plugins from the container-networking-plugins image, so we can stop building them.
/cc @squeed
> Stop building CNI loopback and host-local plugins

- images/node/Dockerfile.rhel
We're still seeing random coredumps / segfaults on rhel7 binaries on rhel8. Disable cgo again.
> Bug 1751954: images: disable cgo

- pkg/network/node/networkpolicy.go
- pkg/network/node/networkpolicy_test.go
In systems with very many namespaces and very many network policies, simply adding new namespaces becomes extremely slow, because, eg, every time you add a new namespace, it needs to compare 10,000 "allow-from-default-namespace" policies against it to see if the namespaceSelectors match.
This fixes that by adding a cache of namespaceSelectors. To avoid having to do complicated cache management, we just empty out the cache any time any Namespace changes. It seems to help a lot; https://github.com/danwinship/sdn/commit/1a5dfd65 has an test on top of this. With the cache, on my laptop, it takes 21ms for the setup and 434ms to complete. With the cache disabled (eg, comment out the `np.nsMatchCache[cacheKey] = namespaces` line in networkpolicy.go), it takes 61ms for the setup and 7.55s to …
> Bug 1752636: networkpolicy: add a namespaceSelector cache

- pkg/network/node/networkpolicy.go
- pkg/network/node/networkpolicy_test.go
The previous fix (#36) did not solve the customer problem because in addition to having thousands of identical copies of the "allow-from-global-namespace" policies (which the cache handles well), they also have thousands of single-namespace-to-single-namespace policies, which the cache didn't optimize as well, because we keep flushing the entire cache even though 99% of the matches didn't change. So this (specifically the second commit) tries to fix that by just making incremental updates to the cache when namespaces change, rather than destroying it every time. See the commit messages for more details
> further NetworkPolicy caching fixes

- pkg/network/node/networkpolicy.go
Add support for IPBlocks in network policy.
ipBlocks in NetworkPolicies allow us to specify CIDR ranges
as ingress sources or egress destinations. Generally these
are cluster-external IPs and will allow you to filter incoming
packets based on the source-ip.
This PR implements ingress ipBlocks in NetworkPolicies.
Support for ipBlocks with except rules will be added via separate PR.
Signed-off-by: Sridhar Gaddam <sgaddam@redhat.com>
Signed-off-by: Janki Chhatbar <jchhatba@redhat.com>
> Add support for IPBlocks

- pkg/network/common/dns.go
- pkg/network/common/dns_test.go
- pkg/network/common/egress_dns.go
- pkg/network/node/egress_network_policy.go
- pkg/network/node/node.go
- pkg/network/node/ovscontroller.go
- pkg/network/proxy/proxy.go
Refactor the datastructures to query DNS names more efficiently as
the same DNS name may appear across multiple policies.
> Make DNS querying more efficient by querying once per dns name

- pkg/network/common/egressip.go
- pkg/network/common/egressip_test.go
- pkg/network/master/egressip.go
- pkg/network/node/egressip.go
If a node lost an egress IP while the sdn process was being restarted, the sdn wouldn't remove the stale egress IP from the node's interface, so you'd end up with two nodes fighting over the packets.
This fixes that by (1) labeling the egress IPs we add so that we can recognize them later, and (2) running a cleanup after we've finished syncing with the master on startup.
(Also, `node.egressIPWatcher` had a mutex that it wasn't using... but it turns out that this isn't a problem because its methods are only called from `common.EgressIPTracker`, which *does* use a mutex when calling the watcher methods. I probably meant to delete the mutex when I split out the `common` parts of the egress IP code, but forgot.)
> Bug 1753216: Clean up egress IPs on startup

- pkg/network/node/node.go
- pkg/network/node/ovscontroller.go
- pkg/network/node/sdn_controller.go
See details at https://bugzilla.redhat.com/show_bug.cgi?id=1760103#c12, but the basic idea is that if SDN gets killed partway through SDN setup, we want to make sure the next SDN pod retries setup from the top rather than mistakenly accepting the half-set-up network.
> Bug 1760103: Adjust SDN setup so AlreadySetUp check will fail on a half-set-up node

- pkg/network/node/networkpolicy.go
- pkg/network/node/networkpolicy_test.go
Backport of #36 and #42 to 4.2. (Clean backport; no changes were needed.)
> Bug 1758232: NetworkPolicy performance fixes [4.2]

- glide.diff
- vendor/k8s.io/client-go/tools/cache/delta_fifo.go
- vendor/k8s.io/client-go/tools/cache/delta_fifo_test.go
Fix DeltaFIFO Replace method to prevent SharedIndexInformers from
missing notifications.
> UPSTREAM 83911: Fix DeltaFIFO Replace method

- images/node/Dockerfile.rhel
handle CGO conditional in Makefile itself and
not in Dockerfile.rhel
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>
@dougbtv @squeed PTAL
> sdn-cni-plugin built without openssl and cgo

- images/node/Dockerfile.rhel
- images/sdn/Dockerfile.rhel
#62 changed the rules for building the CNI plugin, but it was more complicated than it needed to be, and also it only modified the soon-to-be-removed `images/node/Dockerfile.rhel` and not the new `images/sdn/Dockerfile.rhel` (re #59)
/cc @knobunc @lsm5
> Simplify CNI plugin build, copy updated rules to images/sdn/

- pkg/network/master/master.go
- pkg/network/master/subnet_allocator.go
- pkg/network/master/subnet_allocator_test.go
- pkg/network/master/subnets.go
- pkg/network/master/util/subnet_allocator.go
- pkg/network/master/util/subnet_allocator_test.go
This extends SubnetAllocator to support IPv6 ClusterNetworkCIDRs, and then also moves the code from OsdnMaster for handling multiple subnets and makes it part of SubnetAllocator instead.
(Of course, with stock OCP you can't configure an IPv6 ClusterNetwork so this should have no effect on end users at this point, and thus doesn't count as a feature, and would be exempt on IPv6 grounds even if it did.)
ovn-kubernetes currently vendors an older copy of SubnetAllocator (via `"github.com/openshift/origin/pkg/util/netutils"`) and then independently reimplements the multiple CIDR stuff on top of that. My intention was that it could be updated to either copy+paste or vendor this version instead, to provide IPv6 support there as well (and to remove the duplicated multiple CIDR code).
> Add IPv6 support and multiple CIDR support to SubnetAllocator

- glide.diff
- vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
I initially tried to file this as https://github.com/openshift/kubernetes/pull/89 but that's failing CI for infrastructural reasons.
With openshift/origin, they mostly don't modify openshift/kubernetes itself after the initial creation of a new branch, and I think the repo isn't really set up to deal with us wanting to do that. (eg, the branches are protected but the OWNERS files aren't changed from upstream. And CI seems to be broken.). So maybe we should shift to having a clean(er) openshift/kubernetes branch and keeping (at least some) divergences here instead of there?
/cc @dcbw @squeed
> Bug 1768436: UPSTREAM: 74840: kube-proxy: Drop packets in INVALID state

- pkg/network/common/common.go
- pkg/network/common/validation.go
A minor cleanup from my IPv6 branch... I'm sure this made more sense at one point...
> Remove some gratuitous CIDR unparsing and reparsing

- pkg/network/node/pod.go
- pkg/network/node/vnids.go
1. I don't think the NetID logging is ever especially useful
2. The absence of pod create/delete logging is frequently annoying
/hold until the tests run and I can look at the logs
> slightly improve logging

- pkg/openshift-sdn/proxy.go
Works around a nasty bug where having multiple handlers with non-homogeneous resync times causes updates during connection disruption to be missed by one or more handlers.
> proxy: add handler with same ResyncPeriod as shared informer.

- pkg/openshift-sdn/informers.go
It was added to track down the informer issue; we caught it. It causes logs to be way too large.
> Bug 1782847: sdn: undo debug logging

- .gitignore
- Makefile
- images/node/Dockerfile.rhel
- images/sdn/Dockerfile.fedora
- images/sdn/Dockerfile.rhel
- pkg/network/node/pod.go
Due to issues with the host-local plugin coredumping, host-local should be built
in the sdn build process and executed from within the container instead of on the host.
Originally removed in commit: 6d6d35f2f51c84c86b32723e88661c3cd8e379a0
In reference to BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1780387
@squeed recommended naming the binary to `osdn-host-local` to differentiate it. I also went and put it in a directory named `/opt/cni/container-bin` to differentiate it from the host's `/opt/cni/bin` however, I certainly would like any feedback on that naming.
> Bug 1780387: host-local plugin should be built and executed within container

- pkg/network/node/ovscontroller.go
- pkg/network/node/ovscontroller_test.go
If a project has only a deny-all rule and pods running on it,
npNameSpace.inUse was set to false, this commit sets it to true.
If inUse is set to false, the node will not update the
npNamespace if new rules are created until new pods are created.
More details on BZ#1790440
> Bug 1790440: Fix reinitialization of deny-all NetworkPolicy state on restart

- pkg/network/node/egressip.go
- pkg/network/node/iptables.go
Followup to #51; we were removing the stale egress IPs themselves but not the iptables rules associated with them.
I thought about putting the egress IP rules into a separate chain so that we could just flush the chain and then recreate it, which would have been a lot simpler, but then we'd also end up potentially dropping packets on restart, which we've tried to avoid. So I went with this approach.
I was going to add a unit test, but the fake iptables implementation isn't functional enough for this to work. Though... I guess I could use the real iptables implemntation and the fake exec... Anyway, it *does* work.
> Bug 1787488: Clean up stale egress IP iptables rules on startup

- pkg/network/common/dns.go
- pkg/network/common/dns_test.go
- pkg/network/common/egress_dns.go
- pkg/network/node/egress_network_policy.go
- pkg/network/node/node.go
- pkg/network/node/ovscontroller.go
- pkg/network/proxy/proxy.go
Backport from 4.3.
Refactor the datastructures to query DNS names more efficiently as
the same DNS name may appear across multiple policies.
> Bug 1772592: Make DNS querying more efficient by querying once per dns name

- pkg/network/node/ovscontroller.go
- pkg/network/node/ovscontroller_test.go
#96 introduced a bug in NetworkPolicy handling; because the figuring-out-what-VNIDs-there-are-rules-for code was originally used for `FindUnusedVNIDs` which is used by `SyncVNIDRules` to GC unused rules, it had a special case to always claim that VNID 0 was in use, even when it wasn't, because the VNID 0 rules are needed for node-to-pod traffic even if there are no VNID 0 pods present.
However, #96 accidentally made `FindPolicyVNIDs` get that special case too, meaning that when the SDN started up, it would always add VNID 0 to `inUseVNIDs` and so then it would decide that it had already added OVS flows for VNID 0 (even though it hadn't) and so as a result we'd never get any VNID 0 flows and all traffic to VNID 0 pods would be blocked. (CI didn't catch this because none of the CI tests use …
> Bug 1796157: Fix handling of VNID 0 with NetworkPolicy

- pkg/network/proxy/proxy.go
- pkg/network/proxyimpl/hybrid/proxy.go
The missing-proxy-updates problem has been fixed; we don't need to log so much.
> Bug 1804178: Revert excessive proxy logging

- pkg/network/node/node.go
- pkg/network/node/ovscontroller.go
- pkg/network/node/runtime.go
- pkg/network/node/sdn_controller.go
We should kill every (non-hostNetwork) sandbox that we can't reattach
to OVS, but previously we were only killing "every (non-hostNetwork)
sandbox that we knew was previously attached to OVS that we couldn't
reattach to OVS".
> Bug 1806648: Fix pod startup reattach/kill loop

- cmd/sdn-cni-plugin/openshift-sdn_linux.go
The hack to add iptables rules blocking 169.254.169.254 calls iptables directly rather than using k8s's wrapper around it, so it wasn't using `-w`, so if it got called while something else was doing an iptables update, it would fail:
Multus: Err adding pod to network "openshift-sdn": Multus: error in invoke
Delegate add - "openshift-sdn": could not set up pod iptables rules: Another
app is currently holding the xtables lock. Perhaps you want to use the -w option?
> Bug 1810505: Pass -w to iptables when adding anti-metadata-server rules

- pkg/network/node/metrics.go
- pkg/openshift-sdn/proxy.go
On the rebase to kubernetes 1.17 the metrics were moved to
"k8s.io/component-base/metrics/legacyregistry" as part of:
https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/20190404-kubernetes-control-plane-metrics-stability.md
But we were using the old endpoint which was
github.com/prometheus/client_golang/prometheus .
This effort is work in progress so I expect to have problems in future
rebases, most certainly we won't face issues here on the 1.18 and 1.19
rebases.
> Bug 1811739: Fix kube_proxy metrics

- pkg/network/node/node.go
- pkg/openshift-sdn/cmd.go
- pkg/openshift-sdn/proxy.go
- pkg/openshift-sdn/sdn.go
openshift-sdn-node tries to figure out the node IP by resolving the node name as a hostname and/or picking a default IP off the primary network interface. While this made sense historically, there's no point in doing this now since it runs as a pod and so we can just get kubelet to tell us the "official" node IP and should do that instead.
Relatedly, while we are already getting the node name from kubelet, we were passing it in a non-obvious way via environment variable, but we should allow passing it explicitly instead.
(cf https://bugzilla.redhat.com/show_bug.cgi?id=1802557, where we seem to be autodetecting the wrong egress IP)
> Add --node-name and --node-ip flags to openshift-sdn-node

- pkg/network/node/networkpolicy.go
Why this is needed:
Today the SDN networkpolicy code does not create the OVS drop flows for any pod which is created _after and matches_ a "default-deny" networkpolicy. This stems from the fact that `parseNetworkPolicy` only attaches flows to the `npPolicy` should the defined networkpolicy define a `.Spec.Ingress`, which is not always the case, as in the example for the mentioned bug. We need an additional check on the parsed 
`selectedIPs` so that this corner case can be handled and the proper OVS flows created accordingly here: https://github.com/openshift/sdn/blob/master/pkg/network/node/networkpolicy.go#L299
This will need a back-port to 4.1 eventually
> Bug 1813846: handle default-deny rule properely

- pkg/network/node/networkpolicy.go
- pkg/network/node/networkpolicy_test.go
currently if there are two network policies in a namespace that match an
incoming pod refreshNetworkPolicies() will only call updateNetworkPolicy()
on one of them. UpdateNetworkPolicy calls parseNetworkPolicy which updates
the network policy object.
removing the break in refreshNetworkPolicies() will cause
updateNetworkPolicy() to be run against all changed networkpolicies which
will ensure that all changed policies get successfully updated.
also updated the unit tests to expose this issue, so that this issue won't
be exposed again.
https://bugzilla.redhat.com/show_bug.cgi?id=1816394
> Bug 1816394: handle pod updates correctly in networkpolicy

- glide.diff
- vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
The "preserve old health/metrics behavior" patch in #39 was incorrect, but we didn't notice because we don't actually healthcheck kube-proxy when using sdn. However, we *do* healthcheck is when running a standalone kube-proxy, and now that's failing. ~(Also, the metrics should now be indicating that kube-proxy is unhealthy, but no one has noticed that, so I guess we're not alerting on the kube-proxy metrics in 4.3?)~
The problem is that we used to run `syncProxyRules` every `syncPeriod`, whether it was needed or not, and that would poke the health server and metrics to tell it that we were still healthy. With `iptables.Monitor` we no longer need to run `syncProxyRules` when nothing has changed, but that meant we weren't regularly poking the health server. Upstream this was fixed by making …
> Bug 1820778: fix health check in standalone kube-proxy

- pkg/network/node/networkpolicy.go
- pkg/network/node/networkpolicy_test.go
currently if there are two network policies in a namespace that match an
incoming pod refreshNetworkPolicies() will only call updateNetworkPolicy()
on one of them. UpdateNetworkPolicy calls parseNetworkPolicy which updates
the network policy object.
removing the break in refreshNetworkPolicies() will cause
updateNetworkPolicy() to be run against all changed networkpolicies which
will ensure that all changed policies get successfully updated.
also updated the unit tests to expose this issue, so that this issue won't
be exposed again.
4.5 BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1816394
4.4 BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1816392
> [release-4.4] Bug 1816392: handle pod updates correctly in networkpolicy

- HACKING.md
I forgot to update HACKING.md after the migration to go modules.
This includes it.
> Bug 1812052: Update HACKING.md rebase to use go modules

- pkg/network/node/iptables.go
- pkg/network/node/node.go
- pkg/network/proxy/proxy.go
- pkg/network/proxyimpl/hybrid/proxy.go
- pkg/openshift-sdn/cmd.go
- pkg/openshift-sdn/proxy.go
- pkg/openshift-sdn/sdn.go
The iptables proxier has been fixed to not constantly resync its rules when not needed... except that the hybrid proxier was forcing it to do it anyway. Fix that by moving the NodeIPTables monitor up out to the top level of openshift-sdn-node and sharing it between the node and proxy code.
/hold
for testing
> Bug 1822351: Fix hybrid proxier for iptables.Monitor

- pkg/network/node/networkpolicy.go
- pkg/network/node/networkpolicy_test.go
currently if there are two network policies in a namespace that match an
incoming pod refreshNetworkPolicies() will only call updateNetworkPolicy()
on one of them. UpdateNetworkPolicy calls parseNetworkPolicy which updates
the network policy object.
removing the break in refreshNetworkPolicies() will cause
updateNetworkPolicy() to be run against all changed networkpolicies which
will ensure that all changed policies get successfully updated.
also updated the unit tests to expose this issue, so that this issue won't
be exposed again.
4.5BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1816394
4.4BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1816392
4.3BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1816390
> [release-4.3] Bug 1816390: handle pod updates correctly in networkpolicy

- pkg/network/node/networkpolicy.go
- pkg/network/node/networkpolicy_test.go
currently if there are two network policies in a namespace that match an
incoming pod refreshNetworkPolicies() will only call updateNetworkPolicy()
on one of them. UpdateNetworkPolicy calls parseNetworkPolicy which updates
the network policy object.
removing the break in refreshNetworkPolicies() will cause
updateNetworkPolicy() to be run against all changed networkpolicies which
will ensure that all changed policies get successfully updated.
also updated the unit tests to expose this issue, so that this issue won't
be exposed again.
4.5BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1816394
4.4BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1816392
4.3BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1816390
4.2BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1816389
> [release-4.2] Bug 1816389: handle pod updates correctly in networkpolicy

- pkg/network/node/egressip.go
The egressIPTracker has methods that lock eit.mutex and that call
evm functions that lock evm.mutex.
The problem with this is that evm.mutex has to write to the evm.updates
channel which isn't buffered and becomes blocked until
eit.setNodeOffline, which also locks eit.mutex, is running.
This causes a deadlock. By adding a buffered channel with 300 elements
we should avoid the locking problem because "640k ought to be enough
for anybody"
> Bug 1824203: Make egressVXLANMonitor updates channel buffered

- pkg/network/node/networkpolicy.go
- pkg/network/node/vnids.go
When adding a pod, if the NetNamespace isn't found, we'll issue a GET directly to the apiserver and treat it as an ADD. Except we didn't actually handle it correctly, and caused NetworkPolicy to ignore this NetNS forever.
Fixes: rhbz 1825355
> Bug 1825355: node/vnids: Correctly handle case where NetNamespace watch is far behind

- pkg/network/node/egressip.go
- pkg/network/node/vxlan_monitor.go
- pkg/network/node/vxlan_monitor_test.go
The egressIPTracker has methods that lock eit.mutex and that call
evm functions that lock evm.mutex.
The problem with this is that evm.mutex has to write to the evm.updates
channel which isn't buffered and becomes blocked until
eit.setNodeOffline, which also locks eit.mutex, is running.
This causes a deadlock. Initially I tried doing a horrible hack by
making the updates channel huge, however it wasn't enough.
Instead this fix adds a shared nodes list between eit and evm and the
evm uses the updates channel just to notify the eit that there are
updates in the shared list.
> Bug 1824203: Fix egressVXLANMonitor and egressIPTracker deadlock

- pkg/network/node/networkpolicy.go
- pkg/network/node/vnids.go
This is a backport of #134
When adding a pod, if the NetNamespace isn't found, we'll issue a GET
directly to the apiserver and treat it as an ADD. Except we didn't
actually handle it correctly, and caused NetworkPolicy to ignore this
NetNS forever.
Fixes: rhbz 1839107
> Bug 1839107: node/vnids: Correctly handle case where NetNamespace watch is far behind

- pkg/network/node/networkpolicy.go
- pkg/network/node/vnids.go
Backport of #134
When adding a pod, if the NetNamespace isn't found, we'll issue a GET
directly to the apiserver and treat it as an ADD. Except we didn't
actually handle it correctly, and caused NetworkPolicy to ignore this
NetNS forever.
Fixes: rhbz 1389109
/cc @danwinship
> Bug 1839109: [backport-4.3] node/vnids: Correctly handle case where NetNamespace watch is far behind

- pkg/openshift-sdn/proxy.go
If the bind address is an unspecified address, 0.0.0.0 or ::,
kube-proxy uses the nodeIP to detect the IP Family.
It also fixes a minor bug where the IPv6 zero address was not
falling back to the node address.
Signed-off-by: Antonio Ojea <aojeagar@redhat.com>
> kube-proxy use node-ip to detect the IP family

- images/sdn/Dockerfile.fedora
Previous make build-image-sdn-test had a few issues:
1- Build-machinery-go strips binaries by defualt and doesn't produce any
debuginfo.
2- Because we were building the image ocp/builder:golang-1.13, and
running it on fedora, gcore had problems producing core dumps because of
incompatible libthread and libpthread.
Now we build the images directly in fedora, the image is significantly
larger but we now can obtain core dumps and even install delve in the
pod and attach to the live process and we even have the sources.
> build-image-sdn-test: Make binaries debuggable

- pkg/network/node/metrics/metrics.go
- pkg/network/node/node.go
- pkg/network/node/ovs/fake_ovs.go
- pkg/network/node/ovs/ovs.go
- pkg/network/node/ovs/ovs_test.go
- pkg/network/node/pod.go
- pkg/network/node/vnids.go
There can be situations where we cannot program OVS flows because OVS has issues communicating with its unix socket, among other. We should retry these transactions, to make sure we don't loose out on programming OVS correctly because of "flakes". 
EDIT: I am not sure on how often / much we should retry these. Should we use a `DefaultRetry` or do it like this? 
/assign @dcbw @danwinship
> Bug 1851182: Retry commiting OVS transactions in case of failure

- pkg/network/node/ovs/fake_ovs.go
- pkg/network/node/ovs/ovs.go
- pkg/network/node/ovscontroller.go
There is a race condition between ovs and sdn pods. When sdn pod starts, it tries to check if we are `alreadySetup` by checking for 
1. tun0 link being present
2. vxlan port being present
3. resourceVersion table having a len of 1 flow.
If any of these conditions fail, we delete the bridge, and recreate it including syncing all existing pods by collating data from the db and the API server. Imagine a sequence where:
0) SDN has cached ports and interface data in `existingOFPodNetworkInfo`
1) SDN deletes the bridge in `SetupOVS()`
2) ovs daemonset script adds the bridge as a part of save/restore flows.
3) SDN tries to add the bridge, and when trying to create it fails.
At step 3. the pod restarts because the setup couldn't be completed and with that we lose all the cached ports and …
> Add support for --may-exist when adding the bridge in sdn

- pkg/network/node/ovs/ovs.go
- pkg/network/node/ovs/ovs_test.go
Introducing redundancy for OVS commands from the SDN. The previous PR I added only fixed `Transactions` called for flow setup mainly. It would be good to do this for anything and everything, to make sure nothing slips us by. 
/assign @abhat
> Retry all OVS executions, not only transactions

- pkg/network/common/common_test.go
- pkg/network/common/egressip.go
- pkg/network/common/validation.go
If the user sets an invalid egressCIDR value, the API accepts this
and sets it in the hostsubnet field making the user think all went
well. However in the background sdn emits a warning in the logs
saying it ignores the invalid hostsubnet value but the user does
not become aware of this. Upon restarting the sdn-node pod, the pod
fails to come up and barfs that the egressCIDR is invalid.
This patch fixes this by making the sdn-controller wipe out the
invalid egressCIDR/IP field once the validation fails. This is the
same mechanism that the controller uses upon start-up when it comes
across an invalid hostsubnet.
Signed-off-by: Surya Seetharaman <suryaseetharaman.9@gmail.com>
> Bug 1848478:  Invalid egressCIDR value causes sdn pods to fail on startup

- pkg/network/master/egressip.go
- pkg/network/master/master.go
Backport for https://github.com/openshift/sdn/pull/171 https://github.com/openshift/sdn/pull/175
=======
* Refactor logic
* Fix calling nodeInformer in EgressIPManager.
* Add NodeInformer to EgressIP
>  [release-4.5] Bug 1874798: Add NodeInformer to EgressIP

- pkg/network/node/vxlan_monitor_test.go
The test was trying to take advantage of the fact that the updates were guaranteed to happen in order, but forgot that they weren't guaranteed to be _returned_ in order...
/assign @juanluisvaladas
> Bug 1878731: vxlan_monitor_test: fix flake

- pkg/network/master/egressip.go
- pkg/network/master/master.go
Backport for https://github.com/openshift/sdn/pull/171 https://github.com/openshift/sdn/pull/175
=======
* Refactor logic
* Fix calling nodeInformer in EgressIPManager.
* Add NodeInformer to EgressIP
> [release-4.4] Bug 1874799: Add NodeInformer to EgressIP

- pkg/network/node/node.go
- pkg/network/node/ovs/ovs.go
- pkg/network/node/ovs/ovs_test.go
Should I do the same for ovs-subnet as well? I think it makes sense but I doubt anyone actually cares about this in ovs-subnet.
>  Bug 1762580: Enable conntrack for ovs-multitenant unless userspace proxy

- go.mod
- go.sum
- pkg/network/node/vxlan_monitor_test.go
Replaces #190, adds a commit to fix "make verify-deps" which got broken by a disappeared upstream module. (The two commits have nothing to do with each other but I don't feel like filing a bz to let me fix the verify-deps bug separately.)
> Bug 1878787: vxlan_monitor_test: fix flake

- pkg/openshift-sdn/cmd.go
- pkg/openshift-sdn/proxy.go
Spinoff of https://github.com/openshift/cluster-network-operator/pull/819; along with an upcoming CNO PR this will allow us to run openshift-sdn with a standalone kube-proxy for testing
> Allow running openshift-sdn with standalone kube-proxy

- images/kube-proxy/Dockerfile.rhel
Updating kube-proxy builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/kube-proxy.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.
> Updating kube-proxy builder & base images to be consistent with ART

- images/sdn/Dockerfile.rhel
Updating ose-sdn builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ose-sdn.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.
> Updating ose-sdn builder & base images to be consistent with ART

- pkg/network/node/ovscontroller.go
In commit a464217b we changed the flows but forgot to increase the ruleVersion. This breaks upgrades in multitenant.
Also since we're here another little bug that isn't breaking anything right now. Initially 300 was the highest priority but now we have a rule that is 400, make it 1000 so that it's guaranteed that the flow is always evaluated.
> Bug 1878845: Fix ruleversion

- pkg/network/master/vnids.go
While deleting a namespace, we check and delete the netnamespace
and remove the corresponding netid from the masterVNIDMap cache.
However if the netns is deleted before the ns, we return an error
and do not remove it from the cache. Upon recreation of the same
ns/project in the future, a new netns does not get created because
according to the masterVNIDMap cache, that netns is already present.
In this patch we ignore, emit a warning and continue to remove the
netid from the masterVNIDMap cache if the netns is already deleted.
There is no point in returning an error if the objective in the end
is to have the netns deleted. The order of deletion between netns
and ns should not matter.
Signed-off-by: Surya Seetharaman <suryaseetharaman.9@gmail.com>
> Bug 1892376: Ignore if netns is already deleted while deleting ns

- images/sdn/Dockerfile.rhel
We'll not infrequently try to debug, and this is easier and
less error prone than trying to 'oc debug node' and run toolbox.
@stevekuznetsov @danwinship @juanluisvaladas
> Dockerfile: add tcpdump for debugging

- deps.diff
- vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
- vendor/k8s.io/apiserver/pkg/storage/errors.go
- vendor/k8s.io/client-go/tools/cache/reflector.go
two patches taken from openshift/kubernetes are needed to fix this error 
commit: 3704174f95c7311e025284ef30bb56945fa6e7cc
commit: e21e490535fb7a5abd2f6f2c03a11613767e4800
> [release-4.5] UPSTREAM<carry>: Bug 1880341: Fix bug in reflector not recovering from "Too large resource version"

- Makefile
By explicitly defining ldflags we remove the -s flag making the binary
produced by the compiler not stripped.
> Make binaries not stripped

- pkg/network/master/vnids.go
- pkg/network/netid.go
Initially VNIDs 1-9 were forbidden, in OpenShift 4 we need the control
plane components to communicate with each other, so we assigned netid 1 to
it. This is logging an error incorrectly.
> Bug 1897073: Don't throw an error for control plane VNID

- pkg/network/common/dns.go
This was done on master with PR #188. However I closed that, since PR #164 managed to slip in and fix the problem before 188. 164 is however a bit to big and not intended to be back-ported. So let's do this instead. 
Egress network policy should be able to resolve DNS names. If
multiple DNS servers are listed in /etc/resolv.conf and one of these
returns an NXDOMAIN response, we, in turn, return an error and
skip testing any succeeding nameserver.
Instead of returning an error, just continue to the next one.
> Bug 1891454: Fix error handling from DNS nameservers

- pkg/openshift-sdn/proxy.go
This PR reverts commit 12b21f8339b04ebe429cdab71674cad13b70fdef.
It also validates that unsupported feature gates are not accidentally enabled by the daemonset/deployment that launches 
openshift-sdn.
This is gated by the CNO PR: openshift/cluster-network-operator#905 landing first.
> Bug 1906844: Handle unsupported EndpointSlice and EndpointSliceProxying feature gates

- pkg/network/node/networkpolicy.go
For a policy with only Egress Type, the selectedIPs was being
set to an empty IP address. This resulted in attempting to program
a rule in OVS with an empty IP, resulting in an error programming
the flow(s)
Signed-off-by: vpickard <vpickard@redhat.com>
> Bug 1905761: Fix IP list for empty Egress network policy

- pkg/network/node/networkpolicy.go
- pkg/network/node/networkpolicy_test.go
When switching from our pod cache to the informer's, we forgot to filter out the pods that would have been filtered out before. In particular, we forgot to filter out pods that didn't have an IP address assigned yet, causing us to generate invalid flows like
> `flow add table=80, priority=150, reg1=8083932, ip, nw_dst=10.128.2.8, reg0=8083932, ip, nw_src=, tcp, tp_dst=2181,  actions=output:NXM_NX_REG2[]`
(note empty `nw_src=`)
/assign @squeed
> Bug 1914284: Don't try to generate NetworkPolicy flows for non-pod-network pods

- pkg/network/node/networkpolicy.go
- pkg/network/node/networkpolicy_test.go
This reverts commits 2b936ba2c, cad2bb735, 549a799ae, until we resolve the regression (https://bugzilla.redhat.com/show_bug.cgi?id=1914284)
> Bug 1915007: Revert NetworkPolicy performance fixes (4.6)

- cmd/sdn-cni-plugin/openshift-sdn_linux.go
- pkg/network/node/iptables.go
The MCS-blocking rules were too aggressive, and would block connections using 22623/22624 as a source port in some cases.
`--syn` means "SYN and not ACK", so this should make it only block attempts to establish connections to port 22623/4, and not any other traffic involving those ports.
/assign @dcbw
> Bug 1915027: Fix MCS-blocking iptables rules

- pkg/network/node/networkpolicy.go
When an empty egress policy is created, we still need to have connectivity
between pods. Add an empty flow so that the table 80 flow will be added.
Signed-off-by: vpickard <vpickard@redhat.com>
> Bug 1905761: Fix empty egress policy connectivity

- pkg/network/common/dns.go
4.5 back-port of #210 
Egress network policy should be able to resolve DNS names. If
multiple DNS servers are listed in /etc/resolv.conf and one of these
returns an NXDOMAIN response, we, in turn, return an error and
skip testing any succeeding nameserver.
Instead of returning an error, just continue to the next one.
/assign @rcarrillocruz
> Bug 1891455: Fix error handling from DNS nameservers

- pkg/network/node/ovscontroller.go
EgressIP namespaces should only force the egressIP when the pod is the
client. If the pod is the server we want to reply normally.
> Bug 1903414: Do not use egressIP on reply packets

- pkg/network/node/healthcheck.go
The code was using `klog.Fatalf()` as an easy way to log something and then exit, but these days, `klog.Fatalf()` will dump a full stack trace, which makes it look like there's some serious problem.
> Be less melodramatic when restarting due to OVS restart

- pkg/network/common/dns.go
- pkg/network/common/dns_test.go
- pkg/network/common/egress_dns.go
- pkg/network/common/egress_dns_test.go
- pkg/network/common/fake_dns.go
Prior to this PR we have exactly one goroutine to query all the DNS names synchronously.
If a DNS query is slow we'll block the whole synchronization goroutine causing the IP addresses of flows for the rest of the dnsNames to be potentially outdated.
> Bug 1850060: Make DNS queries for egress network policy async

- pkg/network/node/networkpolicy.go
- pkg/network/node/networkpolicy_test.go
Un-reverts #228, with the addition of #240 to fix the bug.
> Bug 1904455: NetworkPolicy performance fixes, v2

- go.mod
- go.sum
- vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
- vendor/modules.txt
* `go.mod`: Bump github.com/openshift/kubernetes.
* `go.sum`:
* `vendor/modules.txt`: Regenerate.
* `vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go` (`syncProxyRules`): Prefer a local endpoint for the cluster DNS service.
> Bug 1919737: Prefer local endpoint for cluster DNS service

- go.mod
- go.sum
- vendor/github.com/gogo/protobuf/proto/text_parser.go
- vendor/golang.org/x/sync/singleflight/singleflight.go
- vendor/modules.txt
The k/k fix is here:
https://github.com/kubernetes/kubernetes/pull/98477
Resolves CVE:
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3121
Here are the steps I used:
go list -m all |grep gogo/protobuf
go get github.com/gogo/protobuf@v1.3.2
go mod vendor
go mod tidy
make
Signed-off-by: vpickard <vpickard@redhat.com>
> Bug 1924527:  CVE-2021-3121 gogo/protobuf lacks certain index validation

- go.mod
- go.sum
- vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
- vendor/modules.txt
Bump the vendored github.com/openshift/kubernetes to pick up https://github.com/openshift/kubernetes/pull/581/commits/3a5282591456b301781c98a60a2bffaf265ed6c0: "UPSTREAM: &lt;carry&gt;: Prefer local endpoint for cluster DNS service".
This bump incidentally picks up commit https://github.com/openshift/kubernetes/commit/6d9f2fe774e6ad19a8c538c76610f3277d05f30f: "UPSTREAM: 95252: Kube-proxy: Perf-fix: Shrink INPUT chain".
* `go.mod`: Bump github.com/openshift/kubernetes.
* `go.sum`:
* `vendor/modules.txt`: Regenerate.
* `vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go`: Bump.
> [release-4.6] Bug 1928773: Prefer local endpoint for cluster DNS service

- pkg/network/node/networkpolicy.go
- pkg/network/node/ovscontroller.go
If a pod makes connections to the same destination pod via a service VIP and
directly to the pod's IP address, it may be the case that both connections
choose the same source port. After the service VIP connection is DNAT-ed to
the destination pod's IP address, both connections will have the same 4-tuple.
When conntrack processes the second connection's TCP SYN and attempts to commit
the conntrack state, the commit fails due to the tuple collision.
To prevent the commit failure, make sure SNAT is done on the source port
during the commit in case of a collision. The use of a fake "0.0.0.0"
address (an undocumented "feature" of OVS that will soon be formalized)
ensures that only the source port will be touched if necessary.
Note that the packets won't be manipulated if they don't need to …
> Bug 1910378: networkpolicy: pass traffic through NAT to handle possible tuple collisions

- go.mod
- go.sum
- vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
- vendor/modules.txt
Bump the vendored github.com/openshift/kubernetes to pick up https://github.com/openshift/kubernetes/pull/604/commits/a18cff1620e79cfce7f212807f93bea87314511a: "UPSTREAM: &lt;carry&gt;: Prefer local endpoint for cluster DNS service".
* `go.mod`: Bump github.com/openshift/kubernetes.
* `go.sum`:
* `vendor/modules.txt`: Regenerate.
* `vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go` (`syncProxyRules`): Prefer a local endpoint for the cluster DNS service.
> Bug 1935297: Prefer local endpoint for cluster DNS service

- pkg/network/node/egressip.go
- pkg/network/node/vxlan_monitor.go
- pkg/network/node/vxlan_monitor_test.go
Currently we incorrectly unmonitoring an egress node whenever
any egress IP stops referencing that node, this is incorrect
because there might be other egress IPs (defined on a separate
namespace) that stills references that egress node. Consider
the following example:
```
oc get hostsubnet
NAME                             HOST                             HOST IP          SUBNET          EGRESS CIDRS   EGRESS IPS
huirwang-45-xslwp-master-0       huirwang-45-xslwp-master-0       172.31.249.251   10.128.0.0/23
huirwang-45-xslwp-master-1       huirwang-45-xslwp-master-1       172.31.249.250   10.130.0.0/23
huirwang-45-xslwp-master-2       huirwang-45-xslwp-master-2       172.31.249.45    10.129.0.0/23                  [172.31.249.205 172.31.249.206]
huirwang-45-xslwp-worker-4hhvt …
```
> Bug 1926931: Fix incorrect unmonitoring of egress nodes

- go.mod
- go.sum
- vendor/github.com/gogo/protobuf/proto/text_parser.go
- vendor/golang.org/x/sync/singleflight/singleflight.go
- vendor/modules.txt
This commit udpates the protobuf version used in sdn to 1.3.2
to address the CVE-2021-3121
Signed-off-by: Aniket Bhat <anbhat@redhat.com>
Backport of #260.
> Bug 1924830: CVE-2021-3121 gogo/protobuf lacks certain index validation

- pkg/network/common/egressip.go
- pkg/network/common/egressip_test.go
- pkg/network/master/egressip.go
- pkg/network/node/egressip.go
- pkg/network/node/egressip_test.go
- pkg/network/node/ovs/fake_ovs.go
- pkg/network/node/ovs/ovs.go
- pkg/network/node/ovs/parse.go
- pkg/network/node/ovs/parse_test.go
- pkg/network/node/ovscontroller.go
- pkg/network/node/ovscontroller_test.go
By using ovs groups transition openshift-sdn from using one egressIP at a time to load-balancing between all available egressIPs
> egress IP traffic load-balancing 

- pkg/openshift-sdn/proxy.go
It can't be disabled in 1.21, and it doesn't matter anyway; it's EndpointSliceProxying that controls whether kube-proxy uses slices.
> Bug 1952079: Don't require EndpointSlice to be disabled

- pkg/network/common/egressip.go
- pkg/network/common/egressip_test.go
The load-balancing feature overlooked removing the check that exists
enforcing that only one egress IP is assigned in automatic assignment
mode. This patch removes that check. The concern with removing this
check is that we might have multiple egress IPs being assigned to the
same node (since any previous implementation didn't have to deal with
that). This is however covered by the verification in `egressIPActive`
which ensures that no more than one egress IP for each namespace is
assigned to every node.
FYI: I have tested this on a local setup with Kind and it works. Both the 
load-balancing feature functions with automatic assignment, and we never
assign more than one egress IP per node for each namespace.
Signed-off-by: Alexander Constantinescu <aconstan@redhat.com>
/assign …
> Bug 1948999: Remove check enforcing single egress IP for automatic assignment

- pkg/network/common/egressip_test.go
`TestEgressCIDRAllocation` was flaking because the tests don't perform
the same logical actions as the code does. The test case finished by
assigning multiple egress IPs to two namespaces (45 and 49) where it
was expected that all egress IPs should be assigned to two different
nodes. The tests are using a test case variable: `changes` which monitors
the state of the test execution during our tests. When the final test
case in `TestEgressCIDRAllocation` was reached: namespace 49 got assigned
two egress IPs to node 3 and node 4, each node assignment called
`SetNamespaceEgressViaEgressIPs` which cumulated the changes for
one node: effectively adding the same expected string twice. This does
not happen during our regular execution since `SetNamespaceEgressViaEgressIPs`
in pkg/network/node …
> Bug 1953530: Fix flaky unit test `TestEgressCIDRAllocation`

- pkg/network/node/node.go
The only interface that needs to be checked is the one tied to the node ip. 
This prevents tainting the node when another interface is added with a lower MTU.
> Bug 1879077: ValidateMTU: check only the interface that holds the node ip

- pkg/network/node/vnids.go
- pkg/network/node/vnids_test.go
Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>
check if newly added netns reuse and existing NetID for a different netns, print a warning message and skip creating this netns
> Bug 1928851: prevent manually creating netns with existing NetID

- pkg/network/node/multitenant.go
- pkg/network/node/networkpolicy.go
- pkg/network/node/node.go
- pkg/network/node/singletenant.go
- pkg/network/node/vnids.go
- pkg/network/node/vnids_test.go
Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>
Bug 1928851 accidentally disabled duplicate NETID unconditionally for network policy and Multitenant which caused CI failure
this PR to limit the new behavior only for NetworkPolicy mode
UT passed with new changes
```
=== RUN   TestEgressIP
--- PASS: TestEgressIP (0.00s)
=== RUN   TestMultipleNamespaceEgressIPs
E0525 19:43:29.678553  325841 egressip.go:388] Multiple namespaces (42, 43) claiming EgressIP 172.17.0.100
E0525 19:43:29.678889  325841 egressip.go:388] Multiple namespaces (42, 44) claiming EgressIP 172.17.0.101
--- PASS: TestMultipleNamespaceEgressIPs (0.00s)
=== RUN   TestNodeIPAsEgressIP
--- PASS: TestNodeIPAsEgressIP (0.00s)
=== RUN   TestDuplicateNodeEgressIPs
E0525 19:43:29.681633  325841 egressip.go:388] Multiple nodes …
```
> Bug 1964625: NETID duplicate check is only required in NetworkPolicy Mode

- images/sdn/Dockerfile.rhel
This was a mistake on my part. PR https://github.com/openshift/sdn/pull/238 bumped OVS on 4.5 to use 2.13 thinking 4.6 was already running 2.13. This is not the case however. So when we upgrade from 4.5 to 4.6 we actually downgrade OVS from 2.13 to 2.11. This is not really that critical since:
- the OVS that really matters runs on the host and does run 2.13 on 4.6 
- the flows written by openshift-sdn are backwards and forwards compatible between 2.11 and 2.13, so it does not actually lead to problems
I just happened to see OVS logging that it was running 2.11 on a OCP 4.6 cluster and was a bit confused.
/assign @dcbw
> Bug 1915849: Bump 4.6 to use OVS 2.13

- pkg/network/node/egressip_test.go
- pkg/network/node/ovs/fake_ovs_test.go
- pkg/network/node/ovscontroller.go
- pkg/network/node/ovscontroller_test.go
A bug was introduced during the implementation of the egress IP with the
traffic load balancing feature, namely: the egress IP flows were evaluated
before the egress network policy ones - just like it was before, however: where
previously the egress IP related flows terminated in a `goto_table:101`
action (allowing the egress network policy flows to determine the final
action) the new feature had it end in `output:tun0`(thus short circuiting
any egress network policy related flows).
Since OVS group actions does not allow for a `goto_table` action, we
need to reverse the table ordering of egress IP and egress network
policy. This patch implements that.
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=1959711 required that
we short circuit the egress IP flows for reply traffic (in case the …
> Bug 1959711: Reverse table order for egress IP and egress network policy set up 

- pkg/network/node/networkpolicy.go
cherry-pick of #233 and #239
[Bugzilla bug 1905761](https://bugzilla.redhat.com/show_bug.cgi?id=1905761) was cloned as [Bugzilla bug 1970046](https://bugzilla.redhat.com/show_bug.cgi?id=1970046)
>  [release-4.6] Bug 1970046: Fix for empty egress policy

- pkg/network/node/networkpolicy.go
- pkg/network/node/networkpolicy_test.go
noticed while trying to debug https://bugzilla.redhat.com/show_bug.cgi?id=1937325, but this is just a test case bug, not a core networkpolicy code bug
> fix a race condition in networkpolicy_test.go

- pkg/network/node/iptables.go
There may be something else on the system running iptables and it
can circumvent "Resource temporarily not avalible" errors to retry
running iptables commands
> Bug 1942122: when assigning and releasing egressIP try more than once before failing

- pkg/openshift-sdn/cmd.go
It will be useful to know what SIGNAL has been sent 
xref: https://bugzilla.redhat.com/show_bug.cgi?id=1956535#c17
Signed-off-by: Antonio Ojea <aojea@redhat.com>
> print signal received by the signal handler

- pkg/network/common/common.go
- pkg/network/proxy/hybridproxier.go
- pkg/network/proxy/hybridproxier_test.go
- pkg/network/proxy/proxy.go
- pkg/network/proxy/proxy_test.go
- pkg/network/proxyimpl/hybrid/proxy.go
- pkg/openshift-sdn/proxy.go
Updates `OsdnProxy`/`HybridProxier` to handle both Endpoints and EndpointSlices, also adding unit tests and doing a bunch of refactoring along the way.
The sdn-level code is compatible with `EndpointSliceProxying` being either enabled or disabled, and also compatible with EndpointSlice support being added to the userspace proxy in the future. (In fact, this PR alone doesn't actually make openshift-sdn use EndpointSlices, because CNO is currently always passing `--feature-gates=EndpointSliceProxying=false`. But once this merges that can be reverted.
(for 4.9)
/cc @aojea
> proxy: filter/delegate EndpointSlices as well as Endpoints

- pkg/network/proxy/hybridproxier.go
- pkg/network/proxy/hybridproxier_test.go
- pkg/network/proxy/proxy_test.go
The code was mistakenly assuming that an EndpointSlice would have the same name as its Service, rather than having a name _based on_ its Service's name.
Also, when HybridProxier gets `OnEndpointSlicesSynced`, it needs to send `OnEndpointsSynced` to the unidling proxy, not `OnEndpointSlicesSynced`.
> Bug 1989122: Fix hybrid proxier with EndpointSlice

- pkg/cmd/openshift-sdn-node/proxy.go
- pkg/cmd/openshift-sdn-node/sdn.go
- pkg/network/node/node.go
- pkg/network/proxy/unidler/unidlerproxy.go
The new `k8s.io/client-go/tools/events` version of `Eventf()` sneakily added a new argument before the trailing message+args, so we're ending up with events with
Action:"The service-port %s:%s needs pods."
Note:"test-service%!(EXTRA string=http)"
This adds an "action" to each event. The documentation is not very useful, but this seems consistent with how it is used in some places in k/k...
----
Additionally, it turns out that openshift-controller-manager is not compatible with openshift-sdn using the new Event API for unidling, because it assumes the `LastTimestamp` field of the event will be set, but this field is deprecated in `eventsv1.Event`, and not set by the convenience APIs. Thus, for now, revert back to using the legacy API for the unidling proxy.
> Bug 1991551: update usage of Events for 1.22 rebase

- pkg/network/node/ovscontroller.go
Previoulsy [we added a flow](https://github.com/openshift/sdn/pull/236) to send reply traffic
to table 101(the ENP table) but in reality ENP
should never match on repy traffic so instead
just send it out.
This seems to already be fixed in 4.8 and greater with https://github.com/openshift/sdn/pull/299 However it can't be 
simply backported due to https://coreos.slack.com/archives/CDCP2LA9L/p1628667498274000?thread_ts=1628601796.223900&cid=CDCP2LA9L
```
That fix was only needed because of a recent feature development for egress IP in openshift-sdn on 4.8 which broke egress network policy, that made it in before 4.8 code freeze though, and the problem never existed on 4.7. So, I am not sure it's safe to backport to 4.7 and risk breaking something else. This seems like it deserves its own fix …
```
> [release-4.7] Bug 1971669: Fix 4.7 SDN Egress Network Policy

- pkg/network/node/iptables.go
Closes  #324
Pablo is out so I took over this PR and made the small fix @danwinship suggested in #324 
It is not needed because vxlan always uses the same destination port (4789 by default) for every packet.
Keeping it can be a source of performance issues on large clusters.
(cherry picked from commit 5c7c5f732f6d5521eab19c429e7fcce0db96812b)
> Bug 1985336: Disable conntrack for vxlan traffic

- images/sdn/Dockerfile.fedora
I forgot to update `Dockerfile.fedora` for the directory renames.
But it had also bit-rotted a bit. And was pointlessly different from `Dockerfile.rhel`. This puts its back in sync (in particular, building things in the same order, using a separate build image, and installing the same rpms). Also, update from Fedora 32 to 34.
```
danw@p1:sdn (dockerfile-fedora)> diff -U1 images/sdn/Dockerfile.{fedora,rhel}
--- images/sdn/Dockerfile.fedora	2021-08-15 12:22:14.684554746 -0400
+++ images/sdn/Dockerfile.rhel	2021-08-15 12:21:42.932280813 -0400
@@ -1,9 +1,2 @@
-# This can be used to build images for testing
-FROM fedora:34 AS builder
-
-RUN INSTALL_PKGS=" \
-      golang \
-      " && \
-    yum install -y --setopt=tsflags=nodocs --setopt=skip_missing_names_on_install=False $INSTALL_PKGS
- …
```
> Fix Dockerfile.fedora

- pkg/cmd/openshift-sdn-node/sdn.go
- pkg/network/node/node.go
pkg/cmd/openshift-sdn-node creates separate recorders for the node and
the proxy, and only the proxy one got updated to the new API, but the
callers of the node one also got (partially) updated to use the new
API even though they were still using an old recorder, resulting in
events like:
"message": "Starting%!(EXTRA string=openshift-sdn done initializing node networking.)",
> Bug 2003859: Fix up event recorder usage (again)

- pkg/cmd/openshift-sdn-node/cmd.go
- pkg/network/common/cniserver/cniserver.go
- pkg/network/common/common.go
- pkg/network/common/egress_dns.go
- pkg/network/common/egressip.go
- pkg/network/common/informers.go
- pkg/network/master/egressip.go
- pkg/network/master/master.go
- pkg/network/master/subnets.go
- pkg/network/master/vnids.go
- pkg/network/node/egress_network_policy.go
- pkg/network/node/egressip.go
- pkg/network/node/metrics/metrics.go
- pkg/network/node/multitenant.go
- pkg/network/node/networkpolicy.go
- pkg/network/node/node.go
- pkg/network/node/ovscontroller.go
- pkg/network/node/pod.go
- pkg/network/node/sdn_controller.go
- pkg/network/node/subnets.go
- pkg/network/proxy/hybridproxier.go
- pkg/network/proxy/proxy.go
- pkg/network/proxy/unidler/unidlersocket.go
- pkg/util/ovs/ovs.go
A long long time ago when openshift-sdn was still in-process in
kubelet/kcm, someone told us we had to use utilruntime.HandleError to
handle errors because it was extensible/configurable/etc. But these
days we know neither openshift-snd-node nor openshift-sdn-controller
makes use of that extensibility/configurability/etc, and using
HandleError() is inconvenient because we usually have to do
"utilruntime.HandleError(fmt.Errorf("...: %v", err))" anyway. So just
stop doing that.
> Replace utilruntime.HandleError() with klog.Errorf()

- pkg/network/master/subnets.go
If we call the function after comparing of old and new node IP adresses, it may cause a failure, because execution stops
immediately if they are equal.
To ensure that the function is always executed, we need to call it before that.
> Run clearInitialNodeNetworkUnavailableCondition earlier

- pkg/cmd/openshift-sdn-controller/network_controller.go
- pkg/network/common/egressip.go
- pkg/network/master/egress_network_policy.go
- pkg/network/master/egress_network_policy_test.go
- pkg/network/master/master.go
- pkg/network/master/metrics/record.go
- pkg/network/master/metrics/register.go
- pkg/network/master/metrics/server.go
Add an insecure HTTP metrics server that serves
metrics on loopback port 29100.
Add metrics to count egress firewalls,
egress firewall rules and egress IPs count.
In order to validate the metrics:
Metric `num_egress_ips`:
1. Configure EgressIP: https://docs.openshift.com/container-platform/4.9/networking/openshift_sdn/assigning-egress-ips.html
2. Exec into SDN pod that is the current LE leader. You can see whos the leader in a config map in the SDN namespace.
3. curl localhost:29100/metrics | grep num_egress_ips
4. You should see an integer from step 3 which represents the total number of egress IPs. This should be the same as the amount you created in step 1.
Metric `num_egress_firewall_rules`:
1. Configure EgressFirewall: https://docs.openshift.com/container-platform/4.9/networking/opens …
> WIP: Metrics: Add server for Egress IP/firewall

- .ci-operator.yaml
- images/kube-proxy/Dockerfile.rhel
- images/sdn/Dockerfile.rhel
- pkg/dependencymagnet/doc.go
The auto-filed #367 and #368 don't verify because `gofmt` 1.17 wants one file to be slightly different.
> update for ART

- pkg/network/node/egressip_test.go
- pkg/network/node/networkpolicy.go
- pkg/network/node/networkpolicy_test.go
- pkg/network/node/ovscontroller.go
- pkg/network/node/ovscontroller_test.go
- pkg/network/node/subnets_test.go
This makes a bunch of updates to the NP code with not a whole lot of visible effect. But:
- it fixes a bug that made us do a lot of useless extra processing whenever you had ipBlock policies
- it adds and updates some unit tests
- it changes the flows we generate for podSelector matches in a way that should have no effect (but _might_ slightly improve efficiency)
- it adds a gigantic doc comment to `ovscontroller.go` explaining how it all works
/cc @astoycos @msherif1234
> NP updates preparing for egress support

- pkg/network/node/egressip_test.go
- pkg/network/node/ovscontroller.go
- pkg/network/node/ovscontroller_test.go
During the implementation of traffic load balancing for egress IP we
simply copied all actions specified on the flow (which did traffic
re-routing to the egress node) in previous versions, to the
group (which did traffic re-routing to multiple egress nodes). However
OVS flows use "OVS action lists", while groups use "OVS action sets", and the
semantics between both differ quite substantially, see:
https://docs.openvswitch.org/en/latest/ref/ovs-actions.7
The impact of this is: whenever a pod initiates an egress
connection and we route that connection to the egress node, we also do
not send the connection to conntrack. This means that the reply packets
will be treated as an incoming new connection which are susceptible to
network policy evaluation. If a network policy is specified which …
> Bug 2024880: [EgressIP] move `ct(commit)` action from OVS group to flow

- pkg/network/node/networkpolicy.go
- pkg/network/node/networkpolicy_test.go
- pkg/util/ranges/doc.go
- pkg/util/ranges/networkpolicy.go
- pkg/util/ranges/networkpolicy_test.go
- pkg/util/ranges/range.go
- pkg/util/ranges/range_test.go
~(WIP because this builds on top of #372 and needs to wait for that to merge first.)~
This finishes up NetworkPolicy feature parity with ovn-kubernetes by implementing ipBlock except rules and port ranges, allowing us to simplify the docs by getting rid of all sdn-vs-ovn notes in the NetworkPolicy docs.
The OpenFlow that this code generates from ipblocks with exceptions is equivalent to what ovn-kubernetes generates.
This also addresses [SDN-1960](https://issues.redhat.com/browse/SDN-1960) by adding warning events when a NetworkPolicy generates a pathological number of OpenFlow rules (which seemed like a good thing to implement along with this, since the new code tends to generate lots of flows...)
> NetworkPolicy ipblock except, port ranges

- pkg/cmd/openshift-sdn-controller/network_controller.go
- pkg/network/master/metrics/register.go
- pkg/network/master/metrics/server.go
Non-leader SDN controller instances do not expose a metrics endpoint.
This causes prometheus to generate an error when attempting to
scrape non-leader SDN controller metrics with a 5XX HTTP error code.
Leader SDN controller metrics are successfully scraped but the
error is unacceptable for non-leader instances.
This PR starts the server for all SDN controller instances but only
the leader instance registers SDN controller specific metrics.
Signed-off-by: Martin Kennelly <mkennell@redhat.com>
A PR in CNO is currently under review to add the `servicemonitor`: https://github.com/openshift/cluster-network-operator/pull/1250
/cc @danwinship
> Bug 2039294: SDN controller metrics cannot be scraped by prometheus

- pkg/network/common/egressip.go
- pkg/network/common/egressip_test.go
- pkg/network/master/egressip.go
- pkg/network/master/master.go
- pkg/network/node/egressip.go
- pkg/network/node/node.go
When validating the .egressIPs defined on a hostSubnet we were using
the informer cache to retrieve the node object and validate that the
egress IP is correctly defined on the cloud subnet. However, the node
informer cache is not guaranteed to be warm when the hostSubnet
informers start, which leads to race events and in case the hostSubnet
informer does not find the node object: a removal of a valid egress IP.
I investigated if there's a way to use WaitForCacheSync as to ensure
that the node informer cache is warm before the hostSubnet informer
starts, however due to the "legacy nature" which openshift-sdn employs
to start its controllers I found the task rather convoluted. Hence, the
solution used in this PR is just to use the kubeClient to fetch the
nodes.
> Bug 2038793: Use the kubeClient instead of the informer cache to fetch nodes for egress IP validation.

- pkg/network/master/egressip.go
Compare node name against the existing CloudPrivateIPConfig instead of the new one.
> Bug 2043802: Fix CloudPrivateIPConfig enqueueing during egressip reassignment

- pkg/network/node/networkpolicy.go
- pkg/network/node/networkpolicy_test.go
The previous fix was incomplete; it covered the case of "some policy isolates all pods for ingress and another policy selects random pods for egress and as a result all pods end up mistakenly isolated for egress", but it didn't cover "some policy isolates _some_ pods for ingress and another policy selects random pods for egress and as a result _some_ pods end up mistakenly isolated for egress".
Confirmed that the new unit tests fails without this fix.
> Bug 2060553: another fix for mixed ingress and egress policies

- pkg/network/node/networkpolicy.go
- pkg/network/node/networkpolicy_test.go
If a namespace contained no policies that applied to the entire namespace, then pods which were selected by at least one ingress-only policy and at least one egress-only policy could end up only half-isolated, such that we would either allow ingress to the pod that should have been blocked, or allow egress from it that should have been blocked.
The basic problem with the last two bugs and this one is that we were trying to combine the ingress-rule-writing and egress-rule-writing together, but it's really hard to do that right. (Specifically, here, the problem is that we needed separate ingress and egress `selectedIPs` sets.) So this splits them apart, which should hopefully work better.
> Bug 2061916: mixed ingress and egress policies can result in half-isolated pods

- pkg/network/node/egressip.go
getEgressLinkDetails uses GetNodeNameByNodeIP to get the egress IP cloud config.
This can fail if egress IP is removed by clearing EgressIPs and EgressCIDRs in HostSubnet since nodesByNodeIP entry will get removed before ReleaseEgressIP is called.
Revert to using GetLinkDetails(eip.localIP) as the additional output of getEgressLinkDetails was ignored anyway.
> Bug 2061919: Fix releasing egress IP in cloud environments

- pkg/network/master/egressip.go
If a node is not ready, continue to process other nodes in the
list after marking it offline instead of returning immediately
since if there are other nodes that are offline at the same
time we need to make sure we mark those nodes as offline as
well to be able to do re-assignment of egressIPs.
Signed-off-by: Surya Seetharaman <suryaseetharaman.9@gmail.com>
/cc @danwinship @kyrtapz @flavio-fernandes
> Bug 2062558: egressip: Continue to process other nodes if a node is not ready

- pkg/cmd/openshift-sdn-cni/openshift-sdn.go
- pkg/cmd/openshift-sdn-cni/openshift-sdn_test.go
- pkg/cmd/openshift-sdn-node/cmd.go
- pkg/network/common/cniserver/cniserver.go
- pkg/network/common/cniserver/cniserver_test.go
- pkg/network/common/common.go
- pkg/network/node/node.go
- pkg/network/node/ovscontroller.go
- pkg/network/node/pod.go
- pkg/network/node/sdn_controller.go
The "MTU is too small" case never happens in normal operation, and giving openshift-sdn-node write access to all Nodes just for that is excessive. So get rid of the tainting, and if we find the MTU is too small then just (a) emit an Event, and (b) exit with an error (which will prevent the node from becoming Ready anyway).
> Bug 2063123: Remove node-tainting for too-small MTU

- pkg/network/node/iptables.go
/cc
In a scenario where an ExternalIP/LoadBalancer is used by a pod with an egress IP configured the packets will be marked and redirected to the egress node using ovs flows.
On the egress node, the traffic will be DNATed to an IP that is in the cluster network. Instead of SNATing to an egress IP masquerade the outgoing packets to ensure that the response traffic is sent back through the same node.
> Bug 2016534: Masquerade in cluster traffic that is marked for egress IP

- pkg/network/node/egressip.go
- pkg/network/node/egressip_test.go
This is needed for egress IP traffic that is DNATed to a local IP(ExternalIP/LoadBalancer).
This type of traffic traverses KUBE-FIREWALL chain which drops packets marked with the default drop bit.
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=2082451#c3
> Bug 2016534: Exclude the default drop bit from egress IP VNID

- pkg/cmd/openshift-sdn-node/cmd.go
- pkg/network/node/node.go
- pkg/network/node/pod.go
- pkg/util/ovs/ovs.go
Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>
test results
```
OCP 4.9 image:
******************sdn-84zqg*************
Plugin Start: 17:28:15.680695
Plugin Ready: 17:28:20.678844
Time diff(s): 5
******************sdn-j6wpf*************
Plugin Start: 17:28:16.139822
Plugin Ready: 17:29:43.829619
Time diff(s): 87
******************sdn-qnjmf*************
Plugin Start: 17:30:57.958794
Plugin Ready: 17:32:12.226418
Time diff(s): 75
******************sdn-qnqdg*************
Plugin Start: 17:33:07.827914
Plugin Ready: 17:34:27.394670
Time diff(s): 80
******************sdn-qz2gm*************
Plugin Start: 17:30:11.963915
Plugin Ready: 17:30:24.910544
Time diff(s): 13
******************sdn-z87rs*************
Plugin Start: 17:28:31.051204
Plugin Ready: 17:28:56.230275
Time diff(s): 25
Clean …
```
> Bug 2052332: use pods cache during reattach processing 

- pkg/network/node/networkpolicy.go
- pkg/network/node/networkpolicy_test.go
in the case where an egress rule has no namespaceSelector and an empty pod Selector we generate a flow fmt.Sprintf("reg1=%d, ", npns.vnid), that is wrong because reg1 is not set at this point.
the egress flows need to be generated using only podIPs rather then VNIDs for egress flows
> OCPBUGS-256: fix network policy egress

- pkg/network/common/kube_list.go
Set ResourceVersion to 0 so that list requests are served from the api server cache instead of etcd.
Keep pagination, as requests may still fallback to etcd if the apiserver cache has not been initialized yet (i.e. apiserver restart).
Ref: https://github.com/kubernetes/enhancements/blob/328e235effab8ba0869586bdb4ee7b10a0ee0801/keps/sig-api-machinery/3157-watch-list/README.md#appendix
Signed-off-by: Jaime Caamaño Ruiz <jcaamano@redhat.com>
> Bug 2050230: pass ResourceVersion:0 for kube List() calls

- pkg/network/node/egressip.go
Sync node egress IP assignment every time an egress IP is removed from the interface.
Even though the IPs should be reassigned quickly there is still a chance for some disruption to the traffic using egress IP.
/cc @jcaamano @cybertron @danwinship 
> OCPBUGS-95: Add node egress IP assignment resync

- pkg/network/node/networkpolicy.go
- pkg/network/node/networkpolicy_test.go
in the case where an egress rule has no namespaceSelector and an empty pod Selector we generate a flow fmt.Sprintf("reg1=%d, ", npns.vnid), that is wrong because reg1 is not set at this point.
the egress flows need to be generated using only podIPs rather then VNIDs for egress flows
clean backport of the master commit
> OCPBUGS-2105: fix network policy egress

- images/iptables-scripts/ip6tables
- images/iptables-scripts/ip6tables-restore
- images/iptables-scripts/ip6tables-save
- images/iptables-scripts/iptables
- images/iptables-scripts/iptables-restore
- images/iptables-scripts/iptables-save
- images/kube-proxy/Dockerfile.rhel
- images/sdn/Dockerfile.fedora
- images/sdn/Dockerfile.rhel
Using the host's iptables was necessary when the container image might have been running on RHEL7 BYOH, but given that's no longer possible, we can clean this up and just use the container's iptables (since both it and the host will be iptables-nft).
> iptables: use container iptables, not host's

- pkg/network/node/networkpolicy.go
There is a race condition where EnsureVNIDRules (via setup in pod.go) is invoked followed by AddNetNamespace which causes default vnid ingress and egress flow rules in table 80 and 27 not getting programmed. This fix ensures these flow rules are programmed though AddNetNamespace is processed at later point of time.
Signed-off-by: Periyasamy Palanisamy <pepalani@redhat.com>
> Handle race condition to setup default vnid flows

- pkg/network/node/networkpolicy.go
- pkg/network/node/networkpolicy_test.go
in the case where an egress rule has no namespaceSelector and an empty pod Selector we generate a flow fmt.Sprintf("reg1=%d, ", npns.vnid), that is wrong because reg1 is not set at this point.
the egress flows need to be generated using only podIPs rather then VNIDs for egress flows
> OCPBUGS-2106: fix network policy egress

- pkg/network/common/egressip.go
- pkg/network/common/egressip_test.go
- pkg/network/master/egressip.go
- pkg/network/node/egressip.go
There are two issues this PR tries to address:
[1] When egress node goes offline and there is **only one** egress IP assigned to a netnamespace the flows will not be removed from the node hosting a matching pod: 
- in auto mode, the flow will get cleared once the sdn-controller removes the egress IP from the hostsubnet
- in manual mode, the pod traffic will still be sent to the egress node
[2] When one egress node goes offline and there is **multiple** egress IPs assigned to a netnamespace the following could happen: 
1. On the pod node SDN detects the egress node as offline, sets `egressNode.offline` to true, and modifies the OVS flows:
```
I0210 13:55:25.625292  148815 egressip.go:350] Node 10.0.130.175 may be offline... retrying
I0210 13:55:27.626969  148815 egressip.go:350] Node …
```
> OCPBUGS-6714: Initialize egress node monitoring struct with previous reachability status

- pkg/network/node/networkpolicy.go
There is a race condition where EnsureVNIDRules (via setup in pod.go) is invoked followed by AddNetNamespace which causes default vnid ingress and egress flow rules in table 80 and 27 not getting programmed. This fix ensures these flow rules are programmed though AddNetNamespace is processed at later point of time.
Signed-off-by: Periyasamy Palanisamy <pepalani@redhat.com>
(cherry picked from commit 04e948660c4d165f87990d05ca227bc68ef46ce1)
> OCPBUGS-6842: Handle race condition to setup default vnid flows

- pkg/cmd/openshift-sdn-node/kube_proxy.go
- pkg/network/node/iptables.go
- pkg/network/node/iptables_test.go
- pkg/network/node/multitenant.go
- pkg/network/node/node.go
- pkg/network/node/ovscontroller.go
- pkg/network/node/ovscontroller_test.go
- pkg/network/node/sdn_controller.go
This was only used for Multitenant mode when using the userspace proxy. But the userspace proxy is gone now, so just remove the pre-conntrack codepaths.
(This also changes Subnet mode to use conntrack mode, but that's pretty much irrelevant.)
/assign @msherif1234
> Drop non-conntrack-based Service support

- pkg/network/common/common.go
- pkg/network/common/common_test.go
- pkg/network/common/kube_list.go
- pkg/network/common/list_pager.go
- pkg/network/master/master.go
- pkg/network/master/subnets.go
- pkg/network/master/vnids.go
- pkg/network/node/egress_network_policy.go
- pkg/network/node/multitenant.go
- pkg/network/node/networkpolicy.go
- pkg/network/node/node.go
- pkg/network/node/vnids.go
- pkg/network/proxy/proxy.go
Using the resource List API without pagination overloads etcd
for a high number of resources. Use pagination with the default page
item count, currently 500.
Set ResourceVersion to 0 so that list requests are served from the api
server cache instead of etcd. Requests may fallback to etcd if the apiserver
cache has not been initialized yet (i.e. apiserver restart).
Ref: https://github.com/kubernetes/enhancements/blob/328e235effab8ba0869586bdb4ee7b10a0ee0801/keps/sig-api-machinery/3157-watch-list/README.md#appendix
> [release-4.10] OCPBUGS-5977: Use pagination and set ResourceVersion to 0 when listing resources

- pkg/network/common/egressip.go
This PR fixes issue tracked via [OCPBUGS-8007](https://issues.redhat.com/browse/OCPBUGS-8007): 
`nil pointer reference on egress IP puts sdn-controllers into crashloop after upgrading to Openshift 4.10.43`
This race is hard to reproduce on it's own, but can be easily reproduced in environments where CNCC is used, by adding an artificial delay in the start function as shown:
```
diff --git a/pkg/network/common/egressip.go b/pkg/network/common/egressip.go
index 56d3f0c32..22616bdaf 100644
--- a/pkg/network/common/egressip.go
+++ b/pkg/network/common/egressip.go
@@ -147,7 +147,11 @@ func (eit *EgressIPTracker) Start(kubeClient kubernetes.Interface, hostSubnetInf
eit.watchNetNamespaces(netNamespaceInformer)        if nodeInformer != nil {
+               time.Sleep(10 * time.Second) …
```
> OCPBUGS-8007: Fix race in Egress IP Tracker start

- pkg/network/node/egress_network_policy.go
When egress network policies are updated they are deleted and recreated. When we are processing the update for egress network policies currently we delete the new version of the network policy as opposed to the old version. If a dnsName is being removed from an egress network policy during an update the dnsName is not in the most recent version of the object and it will not be removed from the egress network policies egressDNS maps.
Plug the leaked data by ensuring that we delete the previous version of the egressNetwork policy and correctly remove the DNS names from the egressDNS object.
> OCPBUGS-1370: save and delete the old egress network policy

- images/sdn/Dockerfile.rhel
This PR proposes to add a build argument to drive the proper openvswitch package to install from the RPM repositories.
This will ease the versions bump and will be helpful for some OKD-related builds when the RPM repositories are not in sync, and some packages version might miss.
cc @vrutkovs @LorbusChris
> OCPBUGS-13717: Use the ovsver build arg to infer the openvswitch short version number

- pkg/network/node/egress_network_policy.go
When egress network policies are updated they are deleted and recreated. When we are processing the update for egress network policies currently we delete the new version of the network policy as opposed to the old version. If a dnsName is being removed from an egress network policy during an update the dnsName is not in the most recent version of the object and it will not be removed from the egress network policies egressDNS maps.
Plug the leaked data by ensuring that we delete the previous version of the egressNetwork policy and correctly remove the DNS names from the egressDNS object.
manual cherry-pick of https://github.com/openshift/sdn/pull/539 to speed the process along
> [release-4.11] OCPBUGS-13917: save and delete the old egress network policy

- pkg/network/node/networkpolicy.go
there is a potential concurrent map read/write in handleAddOrUpdatePod() in pkg/network/node/networkpolicy.go
handleAddOrUpdatePod() has to get the networkPolicyPlugin lock before calling isOnPodNetwork() because that can call getPodIP() which reads the localPodIPs map. If the lock is not grabbed there could be a concurrent read/write of the map
this patch grabs the lock before calling isOnPodNetwork()
> OCPBUGS-13975: fix possible concurrent map read/write

- pkg/network/node/sdn_controller.go
With changes to disable IP forwarding by default with OVNK: https://github.com/openshift/machine-config-operator/pull/3676
OVN to SDN migration is now broken, because pods roll out first that require IP forwarding. IP forwarding for SDN is enabled via MCO node rollout, which happens later.
This change enables IP forwarding in the SDN pod itself if needed.
> OCPBUGS-3176: Enable IP Forwarding if disabled

- pkg/network/node/egress_network_policy.go
When egress network policies are updated they are deleted and recreated. When we are processing the update for egress network policies currently we delete the new version of the network policy as opposed to the old version. If a dnsName is being removed from an egress network policy during an update the dnsName is not in the most recent version of the object and it will not be removed from the egress network policies egressDNS maps.
Plug the leaked data by ensuring that we delete the previous version of the egressNetwork policy and correctly remove the DNS names from the egressDNS object.
manual cherry-pick of https://github.com/openshift/sdn/pull/544 to move things along faster
> [release-4.10] OCPBUGS-13919: save and delete the old egress network policy

- pkg/network/node/networkpolicy.go
manual cherry-pick of https://github.com/openshift/sdn/pull/546
there is a potential concurrent map read/write in handleAddOrUpdatePod() in pkg/network/node/networkpolicy.go
handleAddOrUpdatePod() has to get the networkPolicyPlugin lock before calling isOnPodNetwork() because that can call getPodIP() which reads the localPodIPs map. If the lock is not grabbed there could be a concurrent read/write of the map
this patch grabs the lock before calling isOnPodNetwork()
> [release-4.11] OCPBUGS-14305: fix possible concurrent map read/write

- images/sdn/Dockerfile.rhel
Ensure that we keep a binary at the same place as the older images just in case something expects it there. Really only affects CI due to the way we run our CI upgrade jobs by hacking around with the CNO manifests.
> OCPBUGS-15977: Dockerfile: keep a RHEL-8 CNI shim binary in the default /opt/cni/bin dir

- images/sdn/Dockerfile.rhel
Dockerfile changes to build both rhel8 and rhel9 binaries
Since the shim (openshift-sdn) gets copied to the host OS and
executed in the host mount namespace by CRIO/Multus it needs
to be runtime compatible with the host OS. Running a RHEL9-built
shim on a RHEL8 system doesn't work due to different shared library
dependencies between the two OS versions.
This wasn't a problem before because CGO_ENABLED=0 which essentially
statically linked everything into the binary. But since we actually
need CGO_ENABLED=1 (which ART forces on "official" builds anyway)
to ensure we use OpenSSL's crypto for FIPS compliance, we run into
the OS version problem with our binaries since they are really
always built with CGO_ENABLED=1 anyway.
So... build two separate versions of openshift-sdn and
osdn-host-local …
> Dockerfile changes to build both rhel8 and rhel9 binaries

- images/sdn/Dockerfile.rhel
Since the shim (openshift-sdn) gets copied to the host OS and executed in the host mount namespace by CRIO/Multus it needs to be runtime compatible with the host OS. Running a RHEL8-built shim on a RHEL7 system doesn't work due to different shared library dependencies between the two OS versions.
This wasn't a problem before because CGO_ENABLED=0 which essentially statically linked everything into the binary. But since we actually need CGO_ENABLED=1 (which ART forces on "official" builds anyway) to ensure we use OpenSSL's crypto for FIPS compliance, we run into the OS version problem with our binaries since they are really always built with CGO_ENABLED=1 anyway.
So... build two separate versions of openshift-sdn and osdn-host-local (which is invoked by openshift-sdn shim) in different …
> [release-4.8] OCPBUGS-16253: Dockerfile changes to build both rhel7 and rhel8 binaries

- images/sdn/Dockerfile.rhel
Since the shim (openshift-sdn) gets copied to the host OS and executed in the host mount namespace by CRIO/Multus it needs to be runtime compatible with the host OS. Running a RHEL8-built shim on a RHEL7 system doesn't work due to different shared library dependencies between the two OS versions.
This wasn't a problem before because CGO_ENABLED=0 which essentially statically linked everything into the binary. But since we actually need CGO_ENABLED=1 (which ART forces on "official" builds anyway) to ensure we use OpenSSL's crypto for FIPS compliance, we run into the OS version problem with our binaries since they are really always built with CGO_ENABLED=1 anyway.
So... build two separate versions of openshift-sdn and osdn-host-local (which is invoked by openshift-sdn shim) in different …
> [release-4.7] OCPBUGS-16254: Dockerfile changes to build both rhel7 and rhel8 binaries

- images/sdn/Dockerfile.rhel
Since the shim (openshift-sdn) gets copied to the host OS and executed in the host mount namespace by CRIO/Multus it needs to be runtime compatible with the host OS. Running a RHEL8-built shim on a RHEL7 system doesn't work due to different shared library dependencies between the two OS versions.
This wasn't a problem before because CGO_ENABLED=0 which essentially statically linked everything into the binary. But since we actually need CGO_ENABLED=1 (which ART forces on "official" builds anyway) to ensure we use OpenSSL's crypto for FIPS compliance, we run into the OS version problem with our binaries since they are really always built with CGO_ENABLED=1 anyway.
So... build two separate versions of openshift-sdn and osdn-host-local (which is invoked by openshift-sdn shim) in different …
> [release-4.6] OCPBUGS-16255: Dockerfile changes to build both rhel7 and rhel8 binaries

- pkg/network/master/master.go
- pkg/network/node/node.go
- pkg/network/node/ovscontroller.go
- pkg/network/node/ovscontroller_test.go
During live migration, openshift-sdn nodes will be connected to
ovnkube network as hybrid overlay nodes. The VXLAN packets from
ovnkube node have the same dest_MAC as the both the inner and
outer MAC with the MAC address of the physical interface. In order
to forward the packet to the pod, we swap the inner MAC to the
real MAC of the pod in table 10.
> Live migration: Add flows that allow openshift-sdn to connect to ovnkube

- pkg/network/common/cniserver/cniserver.go
- pkg/network/node/metrics/metrics.go
- pkg/network/node/pod.go
This fixes pod_operations_latency metric for labels setup and teardown as it incorrectly calculating duration while invoking metric's observe method. It also adds new label called e2esetup in metric which provides latency info about total setup processing time for pods.
> Collect pod operation latency metrics properly

- images/sdn/Dockerfile.rhel
This is an cherry-pick of https://github.com/openshift/sdn/pull/534 instead of https://github.com/openshift/sdn/pull/553
> [release-4.13] OCPBUGS-14504: Use the ovsver build arg to infer the openvswitch short version number

- deps.diff
- vendor/github.com/containernetworking/plugins/plugins/ipam/host-local/backend/disk/backend.go
Conform to CIS Benchmarks "1.1.9 Ensure that the Container Network Interface file permissions are set to 600 or more restrictive" https://www.tenable.com/audits/items/CIS_Kubernetes_v1.20_v1.0.1_Level_1_Master.audit:f1717a5dd65d498074dd41c4a639e47d
The fix was merged in containernetworking/plugin (https://github.com/containernetworking/plugins/commit/33ccedc66fc30523f11d480d9d32f33c059fab7d), but we're vendoring a much older version of that repo in sdn and bumping containernetworking/plugins to the latest proved to be not straightforward (https://github.com/openshift/sdn/pull/579) and potentially prone to... regressions.
Let's just apply the small fix directly in the vendored repo to avoid issues.
> OCPBUGS-16788: Create IPAM files with 0600 permissions

- go.mod
- go.sum
- pkg/cmd/openshift-sdn-cni/openshift-sdn.go
- vendor/modules.txt
- vendor/sigs.k8s.io/knftables/.gitignore
- vendor/sigs.k8s.io/knftables/CHANGELOG.md
- vendor/sigs.k8s.io/knftables/CONTRIBUTING.md
- vendor/sigs.k8s.io/knftables/LICENSE
- vendor/sigs.k8s.io/knftables/Makefile
- vendor/sigs.k8s.io/knftables/OWNERS
- vendor/sigs.k8s.io/knftables/README.md
- vendor/sigs.k8s.io/knftables/SECURITY_CONTACTS
- vendor/sigs.k8s.io/knftables/code-of-conduct.md
- vendor/sigs.k8s.io/knftables/error.go
- vendor/sigs.k8s.io/knftables/exec.go
- vendor/sigs.k8s.io/knftables/fake.go
- vendor/sigs.k8s.io/knftables/nftables.go
- vendor/sigs.k8s.io/knftables/objects.go
- vendor/sigs.k8s.io/knftables/transaction.go
- vendor/sigs.k8s.io/knftables/types.go
- vendor/sigs.k8s.io/knftables/util.go
Along with warning about customers using iptables in pods (https://issues.redhat.com/browse/SDN-4114) we need to make sure that we _don't_ use iptables in pods.
This only changes our per-pod iptables rules to use nftables; openshift-sdn still uses iptables in the host network namespace for now.
> SDN-4114: Do per-pod MCS/metadata blocking with nftables rather than iptables

- .snyk
ignore vendor/github.com/containernetworking/plugins/pkg/ns/ns_linux.go to supress scan errors in snyk scan
> OCPBUGS-26084: Fix scan issue
