openshift/sdn

- .gitignore
- Makefile
and most importantly this gives as our first promoted image on merge
/cc @sttts @deads2k
> Fix Makefile and .gitignore

- images/node/Dockerfile
- images/node/Dockerfile.rhel
SDN-488
https://jira.coreos.com/browse/SDN-488
Signed-off-by: Phil Cameron <pcameron@redhat.com>
> Add arping to openshift-sdn image

- cmd/sdn-cni-plugin/openshift-sdn_linux.go
> Route to SDN irrespective if macvlan mode is used or not

- pkg/network/node/node.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1728518
> Untaint node on startup if node is tainted and MTU is ok

- images/node/Dockerfile
- images/node/Dockerfile.rhel
SDN-503 Dockerfiles: verify that packages are installed
https://jira.coreos.com/browse/SDN-503
Signed-off-by: Phil Cameron <pcameron@redhat.com>
> Dockerfiles: verify that packages are installed

- pkg/network/node/egressip.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1731905
> Do not cache egressLink details

- pkg/network/proxy/proxy.go
- pkg/openshift-sdn/proxy.go
Currently the SDN service proxy looks something like this:
waitingProxyHandler
OsdnProxy
HybridProxier
iptables.Proxier
NewUnidlerProxy()
userspace.Proxier
This is kind of insane. This PR squashes the top two levels together.
> Remove one layer of proxy wrapping

- pkg/network/node/networkpolicy.go
Currently if you use an unsupported NetworkPolicy rule (specifically, named ports) in a policy, we treat the policy as though it was default-deny; this was done for the same reason we do similar things when you screw up with joined namespaces; to make it really obvious that something has gone wrong, so that you will notice quickly and fix it.
There are two problems with this, though:
1. If you are creating NetworkPolicies at all, you probably already have a default-deny policy in the namespace, so adding a second one will have no effect anyway.
2. If you *aren't* creating NetworkPolicies on your own, but you have an operator that creates NetworkPolicies for its own pods only, and it uses an unsupported rule, and it recreates its policies any time you delete them, then it ends up forcing a …
> Bug 1768926: Ignore unsupported NetworkPolicy rules, rather than treating them as errors

- HACKING.md
It seemed like this belongs in `HACKING.md`, though the fact that we don't have anything else there yet makes it fit less well...
/assign @squeed
> how to do a Kubernetes rebase

- pkg/network/common/egressip.go
- pkg/network/common/egressip_test.go
- pkg/network/master/egressip.go
- pkg/network/node/egressip.go
> Bug 1772905: [4.2] Clean up egress IPs on startup

- .gitignore
- Makefile
- images/node/Dockerfile.rhel
- images/sdn/Dockerfile.fedora
- images/sdn/Dockerfile.rhel
- pkg/network/node/pod.go
> Bug 1782312: [backport] host-local plugin should be built and executed within container

- OWNERS
This is to improve throughput of merges during EMEA TZ
> Add rcarrillocruz as approver

- pkg/network/node/ovscontroller.go
- pkg/network/node/ovscontroller_test.go
backport of #96 and #103 
/cc @juanluisvaladas
> Bug 1793952: [4.2] Fix reinitialization of deny-all NetworkPolicy state on restart

- pkg/network/node/egressip.go
- pkg/network/node/iptables.go
> Bug 1797042: [4.3] Clean up stale egress IP iptables rules on startup

- pkg/network/node/egressip.go
- pkg/network/node/iptables.go
> Bug 1797043: [4.2] Clean up stale egress IP iptables rules on startup

- pkg/network/node/cniserver/cniserver.go
Signed-off-by: Le Tang <at28997146@163.com>
> Do not check err, but ok for K8S_POD_NAMESPACE and K8S_POD_NAME

- pkg/openshift-sdn/proxy.go
Bring the sdn kube-proxy closer to upstream kube-proxy and respect
EnableProfiling as upstream does. It must be possible to debug the
sdn process and this is consistent with the upstream initialization.
> proxy: It should be possible to enable the profiling endpoint

- pkg/network/node/node.go
- pkg/openshift-sdn/cmd.go
- pkg/openshift-sdn/proxy.go
Follow-up to #120, once https://github.com/openshift/cluster-network-operator/pull/535 merges.
(Also removes `--url-only-kubeconfig`, which is unused since https://github.com/openshift/cluster-network-operator/pull/420.)
> Drop --url-only-kubeconfig, require --node-name / --node-ip

- pkg/network/node/egressip.go
- pkg/network/node/vxlan_monitor.go
- pkg/network/node/vxlan_monitor_test.go
Manual cherry-pick of https://github.com/openshift/sdn/pull/139/
There a conflict but it was trivial.
> [release-4.4] Bug 1840215: Fix egressVXLANMonitor and egressIPTracker deadlock

- pkg/network/node/metrics/metrics.go
- pkg/network/node/node.go
- pkg/network/node/ovs/fake_ovs.go
- pkg/network/node/ovs/ovs.go
- pkg/network/node/ovs/ovs_test.go
- pkg/network/node/pod.go
- pkg/network/node/vnids.go
4.5 backport of https://github.com/openshift/sdn/pull/153 and https://github.com/openshift/sdn/pull/159
/assign @juanluisvaladas @rcarrillocruz
> Bug 1853193: [release-4.5] Backport OVS-retries

- pkg/network/node/ovs/fake_ovs.go
- pkg/network/node/ovs/ovs.go
- pkg/network/node/ovscontroller.go
Back-port of #160 to 4.4
/assign @dcbw @abhat
> Bug 1855119: [release-4.4] Add support for --may-exist when adding the bridge in sdn

- pkg/network/node/metrics/metrics.go
- pkg/network/node/node.go
- pkg/network/node/ovs/fake_ovs.go
- pkg/network/node/ovs/ovs.go
- pkg/network/node/ovs/ovs_test.go
- pkg/network/node/pod.go
- pkg/network/node/vnids.go
4.4 backport of #153 and #159 
/assign @dcbw @JacobTanenbaum
> Bug 1853197: [release-4.4] Backport OVS-retries

- pkg/network/node/metrics/metrics.go
- pkg/network/node/node.go
- pkg/network/node/ovs/fake_ovs.go
- pkg/network/node/ovs/ovs.go
- pkg/network/node/ovs/ovs_test.go
- pkg/network/node/pod.go
- pkg/network/node/vnids.go
4.3 backport of #153 and #159
/assign @danwinship @aojea
> Bug 1853198: [release-4.3] Backport OVS-retries

- pkg/network/node/ovs/fake_ovs.go
- pkg/network/node/ovs/ovs.go
- pkg/network/node/ovscontroller.go
Back-port of #160 to 4.3
/assign @rcarrillocruz  @abhat
> Bug 1859869: [release-4.3] Add support for --may-exist when adding the bridge in sdn

- pkg/network/proxyimpl/hybrid/proxy.go
When the ep is deleted before the svc in unidling proxy mode, the port
does not get deleted and remains stuck. This patch adds a new variable
pendingDeletion to hybrid proxier which keeps track of the svc if the
ep is the one that gets deleted first.
Signed-off-by: Surya Seetharaman <suryaseetharaman.9@gmail.com>
> Bug 1857743: Port stuck open when ep deleted before svc in unidling mode

- pkg/network/master/egressip.go
Currently, EgressIP falls out to another node if the node isn't pinging.
This commit also adds the ability of doing so by checking the node
status.
Signed-off-by: Daniel Mellado <dmellado@redhat.com>
> Bug 1859451: Add NodeInformer to EgressIP

- pkg/openshift-sdn/proxy.go
Currently we are directly using the NewDetectLocalByCIDR function of the
kubeproxy to detect if the traffic is local or not. Kubeproxy does
not support multiple-cidr-ranges. Due to this if a user specifies
multiple-cidr-ranges, CNO simply leaves the kubeproxy.cluster-cidr field
empty. In 4.4 kubeproxy used to emit a warning if an empty cluster-cidr
was passed and ignore the field. In 4.5 kubeproxy still emits a warning
if an empty cluster-cidr is passed. It does this in the getLocalDetector
function. Since getLocalDetector is not exported, we cannot leverage that.
So when we use the NewDetectLocalByCIDR function directly, sdn pods go into
crashloopbackoff because of the empty cidr string.
This patch mimics what kubeproxy does in case of empty cidr string. It emits
a warning and uses the …
> Bug 1877794: Emit a warning and ignore if empty cidr is passed to kubeproxy

- pkg/openshift-sdn/proxy.go
The metrics server is started as part of kube-proxy startup so we were accidentally skipping that when using standalone kube-proxy.
> Run metrics when using standalone kube-proxy

- pkg/network/node/pod.go
Commit b5f89a66 introduced a deadlock on pod creation, but only for multitenant mode.
The fix is to lock runningPods as late as possible.
Fixes: 1890130
> Bug 1890130: fix pod creation deadlock

- images/sdn/Dockerfile.rhel
> sdn: update to OVS 2.13

- pkg/network/node/node.go
- pkg/network/node/ovs/ovs.go
- pkg/network/node/ovs/ovs_test.go
- pkg/network/node/ovscontroller.go
This is a manual cherry pick without conflicts of #189 and #204
> [release-4.5] Bug 1901043: Enable conntrack for ovs-multitenant unless userspace proxy

- pkg/network/node/networkpolicy.go
- pkg/network/node/networkpolicy_test.go
This reverts commits 5ba83a2b6, 6dc30188a, d7bcb5655, until we resolve the regression (https://bugzilla.redhat.com/show_bug.cgi?id=1914284)
> Bug 1915008: Revert NetworkPolicy performance fixes (4.5)

- images/sdn/Dockerfile.rhel
> Bug 1897478: Bump OVS to 2.13

- pkg/network/common/dns.go
- pkg/network/common/dns_test.go
The TTL is guaranteed to be valid for its duration, however, it's not
guaranteed that the DNS server will cache it and always return the same
list of IP addreses for the whole TTL.
For records with large TTL (>30 min) we assume they will always return
the same list of addresses and query them only once every 30 min. We'll
assume rest of the records a TTL of at most 30 seconds.
> Bug 1933711: EgressDNS: Keep short lived records at most 30s

- pkg/network/node/networkpolicy.go
- pkg/network/node/networkpolicy_test.go
This commit treats `openshift-host-network` namespace as having vnid 0 for
network policy match purposes.
Signed-off-by: Aniket Bhat <anbhat@redhat.com>
> Support allow-from-router feature using openshift-host-network namespace

- pkg/network/node/networkpolicy_test.go
Written based on https://bugzilla.redhat.com/show_bug.cgi?id=1937325 but it didn't turn up any bugs. Still a valid test though...
> Add a networkpolicy test with empty namespaceSelector

- pkg/network/node/networkpolicy_test.go
1. There are multiple tests in this file now, so we can't use a global
"synced" variable, or the tests may conflict with each other. (Also,
do some better post-test cleanup now...)
2. There's no way to assert that a networkpolicy sync *didn't* happen,
because it always might be fooled by a sync that is still pending from
a previous operation. That is, if you do:
1. something that might cause two np.syncNamespace() calls
2. assert that a sync happened
3. something that shouldn't cause an np.syncNamespace() call
4. assert that a sync didn't happen
it's possible that the sync at 2 will happen in between the two
syncNamespace() calls in 1, meaning another sync will happen after 2,
fooling the check at 4 into thinking that 3 caused a sync.
It's possible that we could work around this by adding …
> Fix multiple race conditions in networkpolicy_test.go

- pkg/network/node/ovscontroller_test.go
while debugging an upgrade problem I noticed that we introduce a redundant (though eventually harmless) flow in clusters that upgrade from 4.5 to 4.6 because we yet again failed to update `ruleVersion` correctly after making a flow change. This adds a unit test to prevent that from happening again in the future.
/assign @juanluisvaladas
> Add a unit test to ensure we don't change flows without changing ruleVersion

- pkg/network/common/egressip.go
- pkg/network/common/egressip_test.go
sdn-controller wasn't checking if any of the egress IPs requested for a
namespace had already been assigned to a given node. This led to
confusing results in `hostsubnet.egressIPs` where multiple egress IPs
could be assigned to the same node (though in reality no setup was made
because the sdn pod on the node invalidated the assignment). This patch
now fixes that and only has sdn-controller assign the egress IPs that
can, leaving the rest of them out of the result.
Signed-off-by: Alexander Constantinescu <aconstan@redhat.com>
> Bug 1953257: Fix invalid egress IP assignments in sdn-controller

- cmd/sdn-cni-plugin/openshift-sdn_linux.go
- pkg/network/node/iptables.go
> [release-4.6] Bug 1998453: Fix MCS-blocking iptables rules

- pkg/network/common/common_test.go
- pkg/network/common/egressip.go
- pkg/network/common/egressip_test.go
- pkg/network/common/validation.go
- pkg/network/master/egressip.go
- pkg/network/node/egressip.go
- pkg/network/node/egressip_test.go
this is a backport of https://github.com/openshift/sdn/pull/359
>  [release-4.9] Bug 2013707: Remove locking from EgressIPTracker.Ping

- pkg/network/common/egressip_test.go
During the work on #365 we ended up removing the part of the assignment algorithm in `common.go`, which accepted the `fullReallocation` in some cases where more assignments could be made at the expense of changes. We however forgot to remove one check in the unit tests which was based upon this fact. This in turn lead to flakes, since any re-allocation now depends on the state of the previous round of assignments and we can't assume a full assignment anymore.
This has been verified by running: `go test -mod=vendor -race ./... -count 10` with success. I didn't try with a higher count than that though
> Fix flaky check for capacity test for egress IP, and better doc blocs

- go.mod
- pkg/cmd/openshift-sdn-cni/openshift-sdn.go
- pkg/cmd/openshift-sdn-cni/openshift-sdn_test.go
- pkg/cmd/openshift-sdn-node/cmd.go
- pkg/cmd/openshift-sdn-node/sdn.go
- pkg/network/common/cniserver/cniserver.go
- pkg/network/common/cniserver/cniserver_test.go
- pkg/network/node/node.go
- pkg/network/node/pod.go
- pkg/network/node/pod_test.go
- pkg/network/node/sdn_controller.go
- vendor/modules.txt
Implements https://issues.redhat.com/browse/SDN-2553
Depends on https://github.com/openshift/cluster-network-operator/pull/1241
/cc @Kyrtapz @jcaamano
> Handle MTU migration

- pkg/network/master/egressip.go
Fixes two issues:
- The map `cloudPrivateIPConfigCreationQueue` was never initialized anywhere 
- We should only add the `CloudPrivateIPConfig` to the `cloudPrivateIPConfigCreationQueue` when `.spec.node` does not match the `nodeName`. Otherwise when restarting sdn-controller, if there are any egress IP assignments: we will erroneously add items to that queue.
> Bug 2036622: Fix CloudPrivateIPConfig sync on sdn-controller restart

- pkg/network/common/egressip.go
- pkg/network/node/egressip.go
Since GCP uses a [`/32` mask](https://github.com/openshift/enhancements/blob/master/enhancements/network/cloud-egress-ip.md#gcp) it was not possible to assign an egress IP with the current SDN logic:
```E0104 17:55:57.694160    2014 egressip.go:143] Error assigning Egress IP "10.0.128.101": egress IP "10.0.128.101" is not in local network 10.0.128.2/32 of interface ens4```
This change introduces the usage of cloud egress network config to verify if the assignment is valid.
> Bug 2035439: Use cloud egress network config for verifying egress IP in cloud environment

- OWNERS
remove people who are no longer on the team
> clean up OWNERS

- pkg/network/node/networkpolicy.go
The code did not differentiate whether all pods were selected for egress or for ingress.  This changes to track the two separately.
> Bug 2060553: Separate the allPodsSelected into egress and ingress

- pkg/network/node/networkpolicy.go
Blind, mechanical backport of #404, so 4.10 CI presubmits can get going in parallel.
> Bug 2060956: Separate the allPodsSelected into egress and ingress

- pkg/network/node/networkpolicy.go
- pkg/network/node/networkpolicy_test.go
> Bug 2060956: another fix for mixed ingress and egress policies

- go.mod
- go.sum
- vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
- vendor/modules.txt
Depends on https://github.com/openshift/kubernetes/pull/1213
> Bug 2063970: delete stale UDP conntrack entries for loadbalancer IPs

- pkg/network/node/egressip.go
- pkg/network/node/egressip_test.go
- pkg/network/node/iptables.go
This a clean cherry-pick of https://github.com/openshift/sdn/pull/423 and https://github.com/openshift/sdn/pull/428
> [release-4.10] Bug 2082451: Masquerade in cluster traffic that is marked for egress IP

- pkg/cmd/openshift-sdn-node/kube_proxy.go
- pkg/network/proxy/hybridproxier.go
> Bug 2079958: Add TopologyAwareHints support in kube-proxy.

- pkg/network/node/multitenant.go
- pkg/network/node/networkpolicy.go
- pkg/network/node/node.go
- pkg/network/node/pod.go
- pkg/network/node/singletenant.go
Partial revert of https://github.com/openshift/sdn/commit/2d8339c243ad4f9d2118e76cb6f7ec46f7445dbb
Signed-off-by: Nadia Pinaeva <npinaeva@redhat.com>
> Bug 2081562: setup network policy rules during pod creation to fix postStart hook

- pkg/network/common/egressip.go
Signed-off-by: Andreas Karis <ak.karis@gmail.com>
> Enable EgressIP on OpenStack

- go.mod
- go.sum
- vendor/k8s.io/kubernetes/cmd/kube-proxy/app/server.go
- vendor/k8s.io/kubernetes/cmd/kube-proxy/app/server_others.go
- vendor/k8s.io/kubernetes/cmd/kube-proxy/app/server_windows.go
- vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
- vendor/k8s.io/kubernetes/pkg/proxy/winkernel/proxier.go
- vendor/modules.txt
Depends on https://github.com/openshift/kubernetes/pull/1214
> Bug 2063971: delete stale UDP conntrack entries for loadbalancer IPs

- pkg/network/node/networkpolicy.go
When upgrading from OCP 4.10, temporary OpenFlow rules became permanent due to a change in the cookies used for them. Because of that, traffic for pods that should have been blocked only while network policies were being applied was never unblocked.
Reported-at: https://issues.redhat.com/browse/OCPBUGS-998
Signed-off-by: Flavio Fernandes <flaviof@redhat.com>
> OCPBUGS-998: [release-4.11] NetworkPolicy: Remove stale flows that may exist due to an upgrade

- pkg/network/node/egressip.go
This a clean cherry pick of https://github.com/openshift/sdn/pull/463 and https://github.com/openshift/sdn/pull/480.
> [release-4.12] OCPBUGS-4486: Add node egress IP assignment resync 

- OWNERS
Signed-off-by: Martin Kennelly <mkennell@redhat.com>
> Add Tim R and remove Casey from OWNERS

- images/sdn/Dockerfile.fedora
- images/sdn/Dockerfile.rhel
Add /usr/bin/oc to image simiar to openshift-ovn-kubernetes
Signed-off-by: Michael Cambria <mcambria@redhat.com>
> OCPBUGS-5842: Add /usr/bin/oc to image 

- pkg/network/node/networkpolicy.go
Direct cherry-pick of 23ea44043caca595b277510cc85d25d5d1ac1814, no conflicts.
Signed-off-by: Periyasamy Palanisamy <pepalani@redhat.com>
(cherry picked from commit 04e948660c4d165f87990d05ca227bc68ef46ce1) 
(cherry picked from commit 23ea44043caca595b277510cc85d25d5d1ac1814)
> [release-4.11] OCPBUGS-7515: Handle race condition to setup default vnid flows

- pkg/network/node/networkpolicy.go
Direct cherry-pick of https://github.com/openshift/sdn/commit/2f35bbd29daa143b1ce0981277581b498c28bfc1, No conflicts.
> [release-4.10] OCPBUGS-8091: Handle race condition to setup default vnid flows

- images/sdn/Dockerfile.fedora
- images/sdn/Dockerfile.rhel
(cherry picked from commit b0e58ad035810f30b15bdfeecae43bebb33ecc71)
> [release-4.9] OCPBUGS-16894: Add /usr/bin/oc to image simiar to openshift-ovn-kubernetes

- images/sdn/Dockerfile.fedora
- images/sdn/Dockerfile.rhel
Signed-off-by: Michael Cambria <mcambria@redhat.com>
(cherry picked from commit b0e58ad035810f30b15bdfeecae43bebb33ecc71) (cherry picked from commit 1ecde8061509ef62d48866a5edf8fd741d32c6b8)
> [release-4.8] OCPBUGS-16872: Add /usr/bin/oc to image simiar to openshift-ovn-kubernetes

- images/sdn/Dockerfile.fedora
- images/sdn/Dockerfile.rhel
Signed-off-by: Michael Cambria <mcambria@redhat.com>
(cherry picked from commit b0e58ad035810f30b15bdfeecae43bebb33ecc71) (cherry picked from commit 1ecde8061509ef62d48866a5edf8fd741d32c6b8) (cherry picked from commit 1c865093930aea8eb4caa706534e1849ccd5c10e) (cherry picked from commit 4aeadf973ec5c579de64dc989c90e678e0231d56)
> [release-4.6] OCPBUGS-16893: Add /usr/bin/oc to image simiar to openshift-ovn-kubernetes

- images/sdn/Dockerfile.fedora
- images/sdn/Dockerfile.rhel
Signed-off-by: Michael Cambria <mcambria@redhat.com>
(cherry picked from commit b0e58ad035810f30b15bdfeecae43bebb33ecc71) (cherry picked from commit 1ecde8061509ef62d48866a5edf8fd741d32c6b8) (cherry picked from commit 1c865093930aea8eb4caa706534e1849ccd5c10e)
> [release-4.7] OCPBUGS-16891: Add /usr/bin/oc to image simiar to openshift-ovn-kubernetes

- pkg/cmd/openshift-sdn-node/sdn.go
> OCPBUGS-16790: Change the permission of 80-openshift-network.conf to 600

- images/sdn/Dockerfile.rhel
Install openshift clients from RPMs.
> OCPBUGS-28580: Move sdn to RHEL9 base image (attempt #2)
